package obs.rpkg.features.apply.domain;

public enum PublishFailureCode {
    PACKAGE_STATE_NOT_FOUND,
    PACKAGE_IDENTITY_MISMATCH,
    COMMIT_REQUIRED,
    PUBLISH_FAILED,
    PUBLICATION_CONFIRMATION_FAILED,
    REMOTE_BRANCH_DIVERGED,
    STATE_DIVERGED,
    STATE_PERSISTENCE_FAILED,
    UNEXPECTED_LEGACY_FAILURE
}
