import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {GitHubContentsClient,GitHubClientError}=require('../src/github-contents-client.js');
const b64=(text)=>Buffer.from(text,'utf8').toString('base64');
function clientWith(handler){const calls=[];return{calls,client:new GitHubContentsClient({owner:'o',repo:'r',branch:'main',token:'t',transport:async(req)=>{calls.push(req);return handler(req,calls.length-1);}})}}

test('listDirectory and read are explicit GET operations with branch ref',async()=>{const{client,calls}=clientWith((req)=>req.url.includes('/contents/planning/commands?')?{status:200,text:JSON.stringify([{type:'file',path:'planning/commands/a.command.md',name:'a.command.md',sha:'sha-a',size:10}])}:{status:200,text:JSON.stringify({type:'file',path:'planning/commands/a.command.md',sha:'sha-a',content:b64('hello')})});const list=await client.listDirectory('planning/commands');assert.equal(list[0].sha,'sha-a');const file=await client.read('planning/commands/a.command.md');assert.equal(file.content,'hello');assert.equal(calls.length,2);assert.ok(calls.every((call)=>call.method==='GET'&&call.url.includes('ref=main')))});

test('saveVerified updates with base SHA and verifies exact read-back',async()=>{const{client,calls}=clientWith((req)=>{if(req.method==='PUT')return{status:200,text:JSON.stringify({content:{path:'planning/x.md',sha:'new'}})};return{status:200,text:JSON.stringify({type:'file',path:'planning/x.md',sha:'new',content:b64('exact')})}});const result=await client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'old',message:'Update x'});assert.equal(result.sha,'new');const body=JSON.parse(calls[0].body);assert.equal(body.sha,'old');assert.equal(body.branch,'main');assert.equal(calls[1].method,'GET')});

test('404 is classified as not_found without hiding other failures',async()=>{const{client}=clientWith(()=>({status:404,text:JSON.stringify({message:'Not Found'})}));await assert.rejects(()=>client.read('planning/missing.md'),(error)=>error instanceof GitHubClientError&&error.kind==='not_found');});

test('client construction performs no network request',()=>{let calls=0;new GitHubContentsClient({owner:'o',repo:'r',branch:'main',transport:async()=>{calls++;return{status:500,text:'{}'}}});assert.equal(calls,0)});

test('saveVerified recovers a stale-SHA conflict when remote already has intended bytes',async()=>{const{client,calls}=clientWith((req)=>req.method==='PUT'?{status:409,text:JSON.stringify({message:'sha does not match'})}:{status:200,text:JSON.stringify({type:'file',path:'planning/x.md',sha:'fresh',content:b64('exact')})});const result=await client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'stale',message:'Update x'});assert.equal(result.sha,'fresh');assert.equal(result.recoveredAfterConflict,true);assert.equal(result.recoveredAfterUnknownWrite,false);assert.equal(calls.filter((call)=>call.method==='PUT').length,1);assert.equal(calls.filter((call)=>call.method==='GET').length,1)});

test('saveVerified preserves a real conflict when reread bytes differ and never retries PUT',async()=>{const{client,calls}=clientWith((req)=>req.method==='PUT'?{status:422,text:JSON.stringify({message:'sha does not match'})}:{status:200,text:JSON.stringify({type:'file',path:'planning/x.md',sha:'fresh',content:b64('other')})});await assert.rejects(()=>client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'stale',message:'Update x'}),(error)=>error instanceof GitHubClientError&&error.kind==='conflict'&&/differs from the intended file/.test(error.message));assert.equal(calls.filter((call)=>call.method==='PUT').length,1);assert.equal(calls.filter((call)=>call.method==='GET').length,1)});

test('saveVerified still recovers an unknown network result when remote has intended bytes',async()=>{let n=0;const{client}=clientWith((req)=>{n++;if(n===1)throw new GitHubClientError('network_unknown','unknown');return{status:200,text:JSON.stringify({type:'file',path:'planning/x.md',sha:'fresh',content:b64('exact')})}});const result=await client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'old',message:'Update x'});assert.equal(result.recoveredAfterUnknownWrite,true);assert.equal(result.recoveredAfterConflict,false)});

test('saveVerified preserves conflict when post-conflict reread cannot verify remote content',async()=>{let n=0;const{client,calls}=clientWith((req)=>{n++;if(req.method==='PUT')return{status:409,text:JSON.stringify({message:'sha does not match'})};return{status:503,text:JSON.stringify({message:'unavailable'})}});await assert.rejects(()=>client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'stale',message:'Update x'}),(error)=>error instanceof GitHubClientError&&error.kind==='conflict'&&/could not be verified/.test(error.message));assert.equal(calls.filter((call)=>call.method==='PUT').length,1);assert.equal(calls.filter((call)=>call.method==='GET').length,1)});

test('publishFilesAtomic creates blobs/tree/one commit and advances branch ref once',async()=>{const head='1111111111111111111111111111111111111111',tree='2222222222222222222222222222222222222222',newTree='3333333333333333333333333333333333333333',commit='4444444444444444444444444444444444444444';let refReads=0,blobN=0;const{client,calls}=clientWith((req)=>{if(req.method==='GET'&&req.url.includes('/git/ref/heads/main')){refReads++;return{status:200,text:JSON.stringify({object:{sha:refReads===1?head:commit}})}}if(req.method==='GET'&&req.url.includes(`/git/commits/${head}`))return{status:200,text:JSON.stringify({sha:head,tree:{sha:tree}})};if(req.method==='POST'&&req.url.endsWith('/git/blobs'))return{status:201,text:JSON.stringify({sha:`b${++blobN}`})};if(req.method==='POST'&&req.url.endsWith('/git/trees'))return{status:201,text:JSON.stringify({sha:newTree})};if(req.method==='POST'&&req.url.endsWith('/git/commits'))return{status:201,text:JSON.stringify({sha:commit})};if(req.method==='PATCH'&&req.url.includes('/git/refs/heads/main'))return{status:200,text:JSON.stringify({object:{sha:commit}})};throw new Error(`unexpected ${req.method} ${req.url}`)});const result=await client.publishFilesAtomic({files:[{path:'planning/a.md',content:'A'},{path:'planning/b.md',content:'B'}],message:'Bulk',expectedHeadSha:head});assert.equal(result.commitSha,commit);assert.deepEqual(result.files,['planning/a.md','planning/b.md']);assert.equal(calls.filter((call)=>call.method==='POST'&&call.url.endsWith('/git/commits')).length,1);assert.equal(calls.filter((call)=>call.method==='PATCH').length,1);const treeBody=JSON.parse(calls.find((call)=>call.method==='POST'&&call.url.endsWith('/git/trees')).body);assert.equal(treeBody.base_tree,tree);assert.deepEqual(treeBody.tree.map((row)=>row.path),['planning/a.md','planning/b.md'])});

test('publishFilesAtomic fails closed when branch head changed after preview',async()=>{const expected='1111111111111111111111111111111111111111',remote='9999999999999999999999999999999999999999';const{client,calls}=clientWith((req)=>({status:200,text:JSON.stringify({object:{sha:remote}})}));await assert.rejects(()=>client.publishFilesAtomic({files:[{path:'planning/a.md',content:'A'}],message:'Bulk',expectedHeadSha:expected}),(error)=>error instanceof GitHubClientError&&error.kind==='conflict'&&/changed after publish preview/.test(error.message));assert.equal(calls.filter((call)=>call.method!=='GET').length,0)});

test('updateBranchRef recovers an unknown PATCH only when branch head proves the prepared commit',async()=>{const commit='4444444444444444444444444444444444444444';let n=0;const{client}=clientWith((req)=>{n++;if(req.method==='PATCH')throw new GitHubClientError('network_unknown','unknown');return{status:200,text:JSON.stringify({object:{sha:commit}})}});const result=await client.updateBranchRef(commit);assert.equal(result.recoveredAfterUnknownWrite,true);assert.equal(n,2)});
