import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {GitHubContentsClient,GitHubClientError}=require('../src/github-contents-client.js');
const b64=(text)=>Buffer.from(text,'utf8').toString('base64');
function clientWith(handler){const calls=[];return{calls,client:new GitHubContentsClient({owner:'o',repo:'r',branch:'main',token:'t',transport:async(req)=>{calls.push(req);return handler(req,calls.length-1);}})}}

test('listDirectory and read are explicit GET operations with branch ref',async()=>{const{client,calls}=clientWith((req)=>req.url.includes('/contents/planning/commands?')?{status:200,text:JSON.stringify([{type:'file',path:'planning/commands/a.command.md',name:'a.command.md',sha:'sha-a',size:10}])}:{status:200,text:JSON.stringify({type:'file',path:'planning/commands/a.command.md',sha:'sha-a',content:b64('hello')})});const list=await client.listDirectory('planning/commands');assert.equal(list[0].sha,'sha-a');const file=await client.read('planning/commands/a.command.md');assert.equal(file.content,'hello');assert.equal(calls.length,2);assert.ok(calls.every((call)=>call.method==='GET'&&call.url.includes('ref=main')))});

test('saveVerified updates with base SHA and verifies exact read-back',async()=>{const{client,calls}=clientWith((req)=>{if(req.method==='PUT')return{status:200,text:JSON.stringify({content:{path:'planning/x.md',sha:'new'}})};return{status:200,text:JSON.stringify({type:'file',path:'planning/x.md',sha:'new',content:b64('exact')})}});const result=await client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'old',message:'Update x'});assert.equal(result.sha,'new');const body=JSON.parse(calls[0].body);assert.equal(body.sha,'old');assert.equal(body.branch,'main');assert.equal(calls[1].method,'GET')});

test('404 is classified as not_found without hiding other failures',async()=>{const{client}=clientWith(()=>({status:404,text:JSON.stringify({message:'Not Found'})}));await assert.rejects(()=>client.read('planning/missing.md'),(error)=>error instanceof GitHubClientError&&error.kind==='not_found');});

test('client construction performs no network request',()=>{let calls=0;new GitHubContentsClient({owner:'o',repo:'r',branch:'main',transport:async()=>{calls++;return{status:500,text:'{}'}}});assert.equal(calls,0)});

test('saveVerified recovers a stale-SHA conflict when remote already has intended bytes',async()=>{const{client,calls}=clientWith((req)=>req.method==='PUT'?{status:409,text:JSON.stringify({message:'sha does not match'})}:{status:200,text:JSON.stringify({type:'file',path:'planning/x.md',sha:'fresh',content:b64('exact')})});const result=await client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'stale',message:'Update x'});assert.equal(result.sha,'fresh');assert.equal(result.recoveredAfterConflict,true);assert.equal(result.recoveredAfterUnknownWrite,false);assert.equal(calls.filter((call)=>call.method==='PUT').length,1);assert.equal(calls.filter((call)=>call.method==='GET').length,1)});

test('saveVerified preserves a real conflict when reread bytes differ and never retries PUT',async()=>{const{client,calls}=clientWith((req)=>req.method==='PUT'?{status:422,text:JSON.stringify({message:'sha does not match'})}:{status:200,text:JSON.stringify({type:'file',path:'planning/x.md',sha:'fresh',content:b64('other')})});await assert.rejects(()=>client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'stale',message:'Update x'}),(error)=>error instanceof GitHubClientError&&error.kind==='conflict'&&/differs from the intended file/.test(error.message));assert.equal(calls.filter((call)=>call.method==='PUT').length,1);assert.equal(calls.filter((call)=>call.method==='GET').length,1)});

test('saveVerified still recovers an unknown network result when remote has intended bytes',async()=>{let n=0;const{client}=clientWith((req)=>{n++;if(n===1)throw new GitHubClientError('network_unknown','unknown');return{status:200,text:JSON.stringify({type:'file',path:'planning/x.md',sha:'fresh',content:b64('exact')})}});const result=await client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'old',message:'Update x'});assert.equal(result.recoveredAfterUnknownWrite,true);assert.equal(result.recoveredAfterConflict,false)});

test('saveVerified preserves conflict when post-conflict reread cannot verify remote content',async()=>{let n=0;const{client,calls}=clientWith((req)=>{n++;if(req.method==='PUT')return{status:409,text:JSON.stringify({message:'sha does not match'})};return{status:503,text:JSON.stringify({message:'unavailable'})}});await assert.rejects(()=>client.saveVerified({path:'planning/x.md',content:'exact',baseSha:'stale',message:'Update x'}),(error)=>error instanceof GitHubClientError&&error.kind==='conflict'&&/could not be verified/.test(error.message));assert.equal(calls.filter((call)=>call.method==='PUT').length,1);assert.equal(calls.filter((call)=>call.method==='GET').length,1)});
