import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const codec=require('../src/command-definition-codec.js');
const catalog=require('../src/command-catalog.js');
const helper=require('../src/helper-library-codec.js');
const body=require('../src/command-body.js');
const semantic=require('../src/semantic-projections.js');
const repositoryCatalog=require('../src/repository-catalog-service.js');
const currentUseCases=semantic.normalizeUseCaseDefinitions(require('../seed/use-cases.json').items);
const currentSemanticComponents=semantic.normalizeSemanticComponents(require('../seed/semantic-components.json').items);
const currentScenarios=semantic.normalizeScenarios(require('../seed/scenarios.json').items);
globalThis.ObsPlanningHelper=Object.assign({},codec,catalog,helper,body,semantic,repositoryCatalog);
const state=require('../src/planning-helper-state.js');
Object.assign(globalThis.ObsPlanningHelper,state);
const runtime=require('../src/planning-helper-runtime.js');
function def(id='a',command=id){return codec.normalizeCommandDefinition({schemaVersion:1,id,file:`${id}.command.md`,command,englishName:`${id} english`,commandFamily:[command],description:'desc',meaning:'meaning',activeContextBehavior:'active',traversalReadMode:'targeted',ownerFiles:[],expectedOutput:'output',permissionMode:'read-only',keyReminders:['remember'],userTarget:'<target>',palette:true,refinements:[]})}
function helperItem(kind,id,text='text'){return helper.normalizeHelperLibraryItem({kind,id,title:`${kind} ${id}`,text,createdAt:'2026-08-16T00:00:00Z',updatedAt:'2026-08-16T00:00:00Z'})}
function snapshot(){const a=def('a'),hc=helperItem('command','hc'),p=helperItem('prompt','p');return state.normalizePlanningHelperLocalSnapshot({schemaVersion:state.LOCAL_SNAPSHOT_SCHEMA_VERSION,savedAt:'2026-08-16T00:00:00Z',planningCommands:[state.normalizeCommandRecord({definition:a,repositoryKnown:true,repositorySha:'sha-a'})],helperItems:[state.normalizeHelperRecord({item:hc,repositoryKnown:false}),state.normalizeHelperRecord({item:p,repositoryKnown:true,repositorySha:'sha-p'})],useCases:currentUseCases,useCaseCatalogSha:'uc-sha',semanticComponents:currentSemanticComponents,semanticComponentCatalogSha:'semantic-sha',scenarios:currentScenarios,scenarioCatalogSha:'scenario-sha',catalogOrder:{}})}

test('repository inventory compares commands, Use Cases and prompts without fetching bodies',()=>{const local=snapshot();const inventory=runtime.compareRepositoryInventory(local,{commands:[{kind:'planning-command',path:'planning/commands/a.command.md',sha:'sha-a'},{kind:'planning-command',path:'planning/commands/b.command.md',sha:'sha-b'}],useCases:currentUseCases,useCaseSha:'uc-sha',helperItems:[{kind:'command',path:'planning/helper-library/commands/remote.helper-command.md',sha:'x'},{kind:'prompt',path:'planning/helper-library/prompts/p.prompt.md',sha:'sha-p'}]});assert.equal(inventory.planningCommands.local,1);assert.equal(inventory.planningCommands.remote,2);assert.deepEqual(inventory.planningCommands.remoteOnly,['planning/commands/b.command.md']);assert.equal(inventory.useCases.common,currentUseCases.length);assert.deepEqual(inventory.helperCommands.localOnly,['planning/helper-library/commands/hc.helper-command.md']);assert.equal(inventory.prompts.common,1)});

test('repository inventory reports known catalog SHA changes',()=>{const inventory=runtime.compareRepositoryInventory(snapshot(),{commands:[{kind:'planning-command',path:'planning/commands/a.command.md',sha:'changed'}],useCases:currentUseCases,useCaseSha:'new-uc',helperItems:[{kind:'prompt',path:'planning/helper-library/prompts/p.prompt.md',sha:'sha-p'}]});assert.deepEqual(inventory.planningCommands.knownChanged,['planning/commands/a.command.md']);assert.deepEqual(inventory.useCases.knownChanged,['seed/use-cases.json'])});

test('sync merge adds only missing repository records and never overwrites same-path/same-id local records',()=>{const local=snapshot(),b=def('b'),remotePrompt=helperItem('prompt','remote','remote text'),newUc={id:'UC-NEW',label:'New UC',description:'new',sources:['planning/use-case-registry.md'],instruction:'Resolve current owner.',target:'<new>',manualInvocation:true,trigger:'x',result:'y'};const merged=runtime.mergeRemoteMissing(local,{commands:[{path:'planning/commands/a.command.md',sha:'remote-a',definition:{...def('a'),description:'REMOTE SHOULD NOT WIN'},rawContent:codec.renderCommandDefinitionDocument({...def('a'),description:'REMOTE SHOULD NOT WIN'})},{path:'planning/commands/b.command.md',sha:'sha-b',definition:b,rawContent:codec.renderCommandDefinitionDocument(b)}],helperItems:[{path:helper.helperLibraryTargetPath(remotePrompt),sha:'sha-r',item:remotePrompt,rawContent:helper.renderHelperLibraryDocument(remotePrompt)}],useCases:[newUc]});const materialized=runtime.materializeSnapshot(merged.snapshot);assert.equal(materialized.commandById.get('a').definition.description,'desc');assert.ok(materialized.commandById.has('b'));assert.ok(materialized.helperByKey.has('prompt:remote'));assert.ok(materialized.useCases.some((u)=>u.id==='UC-NEW'));assert.equal(merged.addedCommands.length,1);assert.equal(merged.addedHelpers.length,1);assert.equal(merged.addedUseCases.length,1)});

test('invocation preparation materializes only explicitly selected side effects at action time',async()=>{const calls=[],operations={async applyCommandSideEffects(id,text,options){calls.push([id,text,options.effectIds]);return options.effectIds.length?`${text}\n\nSIDE`:text;}};assert.equal(await runtime.prepareInvocationBody('BASE','replacement_archive.create',{},operations),'BASE');assert.equal(await runtime.prepareInvocationBody('BASE','replacement_archive.create',{effectIds:['capture-chat-context']},operations),'BASE\n\nSIDE');assert.deepEqual(calls,[['replacement_archive.create','BASE',[]],['replacement_archive.create','BASE',['capture-chat-context']]]);});

test('clipboard/composer insertion path remains network-agnostic',async()=>{const calls=[];const message=await runtime.insertWithClipboard('BODY','Inserted','cmd',{copyText(text){calls.push(['copy',text]);return true},insertIntoComposer(text,id){calls.push(['insert',text,id]);return{ok:true}}});assert.match(message,/clipboard ready/);assert.deepEqual(calls,[['copy','BODY'],['insert','BODY','cmd']])});

test('local command import/edit clears exact repository evidence only when bytes change',()=>{const original=def('repo-cmd','repo cmd');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:original,repositoryKnown:true,repositorySha:'remote-sha'})]});const changed={...original,description:'locally changed'};const changedMerge=runtime.mergeChatImport(local,{definitions:[changed],helperItems:[]},'import');assert.equal(changedMerge.snapshot.planningCommands[0].repositoryKnown,false);assert.equal(changedMerge.snapshot.planningCommands[0].repositorySha,'');const sameMerge=runtime.mergeChatImport(local,{definitions:[original],helperItems:[]},'import');assert.equal(sameMerge.snapshot.planningCommands[0].repositoryKnown,true);assert.equal(sameMerge.snapshot.planningCommands[0].repositorySha,'remote-sha')});

test('local helper save preserves evidence on no-op and clears it on edit',()=>{const item=helperItem('prompt','same','text');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[],helperItems:[state.normalizeHelperRecord({item,repositoryKnown:true,repositorySha:'sha-1'})]});const unchanged=runtime.prepareLocalHelperSave(local,{kind:'prompt',id:'same',title:item.title,text:item.text,createdAt:item.createdAt},'2026-08-17T00:00:00Z');assert.equal(unchanged.changed,false);assert.equal(unchanged.record.repositorySha,'sha-1');const changed=runtime.prepareLocalHelperSave(local,{kind:'prompt',id:'same',title:item.title,text:'new',createdAt:item.createdAt},'2026-08-17T00:00:00Z');assert.equal(changed.changed,true);assert.equal(changed.record.repositoryKnown,false);assert.equal(changed.record.repositorySha,'')});

test('verified remote result remains success when only local evidence persistence fails',async()=>{const result=await runtime.persistVerifiedRepositoryResult(async()=>{throw new Error('quota')},{},{ok:true,action:'update',path:'x',sha:'remote-sha'},{owner:'o',repo:'r',branch:'main'},()=>({promptEntries:['old']}));assert.equal(result.ok,true);assert.equal(result.sha,'remote-sha');assert.equal(result.localSnapshotUpdated,false);assert.match(result.localSnapshotError,/quota/)});

test('repository source change clears exact repository evidence but keeps local data',()=>{const cleared=runtime.clearRepositoryEvidence(snapshot());assert.equal(cleared.planningCommands[0].definition.id,'a');assert.equal(cleared.planningCommands[0].repositoryKnown,false);assert.equal(cleared.helperItems.length,2);assert.equal(cleared.useCaseCatalogSha,'');assert.equal(cleared.catalogOrderSha,'')});

test('restore reconciles repository-backed records but preserves local-only content without inventing SHA',()=>{const remoteOld=def('remote-old','remote old'),remoteKeep=def('remote-keep','remote keep'),localOnly=helperItem('prompt','local-only','keep me');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:remoteOld,repositoryKnown:true,repositorySha:'old-sha'})],helperItems:[state.normalizeHelperRecord({item:localOnly,repositoryKnown:false})]});const merged=runtime.mergeChatImport(local,{definitions:[remoteKeep],helperItems:[]},'restore');assert.equal(merged.removedRepositoryCommands,1);assert.equal(merged.snapshot.planningCommands[0].definition.id,'remote-keep');assert.equal(merged.snapshot.planningCommands[0].repositorySha,'');assert.equal(merged.snapshot.helperItems[0].item.id,'local-only')});

test('planning command draft edit preserves tracked provenance and cannot rename id/file in place',()=>{const original=def('tracked','tracked');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:original,repositoryKnown:true,repositoryTracked:true,repositorySha:'sha'})]});const changed={...original,description:'changed locally'};const prepared=runtime.prepareLocalCommandSave(local,changed,'tracked');assert.equal(prepared.record.repositoryKnown,false);assert.equal(prepared.record.repositoryTracked,true);assert.equal(prepared.record.repositorySha,'');assert.throws(()=>runtime.prepareLocalCommandSave(local,{...original,id:'renamed',file:'renamed.command.md'},'tracked'),/cannot change its id or file/)});

test('local Delete hides/removes catalog rows and explicit sync can restore a deleted command',()=>{const local=snapshot();const deleted=runtime.deleteLocalCommandFromSnapshot(local,'a');assert.equal(deleted.planningCommands.some((r)=>r.definition.id==='a'),false);assert.deepEqual(deleted.hiddenCommandIds,['a']);const definition=def('a');const merged=runtime.mergeRemoteMissing(deleted,{commands:[{path:'planning/commands/a.command.md',sha:'fresh',definition,rawContent:codec.renderCommandDefinitionDocument(definition)}]});assert.equal(merged.snapshot.planningCommands.some((r)=>r.definition.id==='a'),true);assert.deepEqual(merged.snapshot.hiddenCommandIds,[])});

test('local Use-Case hide does not alter repository-backed semantic catalog',()=>{const local=snapshot(),id='UC-IDTSPE-COMPOSE-CURRENT-WORK';assert.ok(currentUseCases.some((u)=>u.id===id));const next=runtime.deleteLocalUseCaseFromSnapshot(local,id);assert.ok(next.hiddenUseCaseIds.includes(id));assert.equal(runtime.materializeSnapshot(next).useCaseEntries.some((e)=>e.id===id),false);assert.ok(next.useCases.some((u)=>u.id===id))});

test('every current UC projects to exactly one stable semantic command card',()=>{const memory=runtime.materializeSnapshot(snapshot());for(const uc of currentUseCases){const matches=memory.commandEntries.filter((e)=>e.id===`uc:${uc.id}`);assert.equal(matches.length,1,uc.id);assert.equal(matches[0].canonicalId,uc.id);assert.ok(['DIRECT CURRENT','GENERIC CURRENT'].includes(matches[0].stateLabel),uc.id)}});

test('projection-only semantic UC cards are not editable/deletable command definitions',()=>{const local=snapshot(),memory=runtime.materializeSnapshot(local),generated=memory.commandEntries.find((e)=>e.semanticKind==='USE_CASE'&&!e.directCommandId);assert.ok(generated);assert.equal(generated.entityType,'semantic-command');assert.throws(()=>runtime.deleteLocalCommandFromSnapshot(local,generated.id),/not found/);assert.ok(memory.useCases.some((u)=>u.id===generated.canonicalId))});

test('Favorites are local stable-ID projections',()=>{let local=snapshot();local=runtime.toggleFavoriteCommandInSnapshot(local,'a');assert.deepEqual(local.favoriteCommandIds,['a']);const uc='UC-IDTSPE-COMPOSE-CURRENT-WORK';local=runtime.toggleFavoriteUseCaseInSnapshot(local,uc);assert.deepEqual(local.favoriteUseCaseIds,[uc]);local=runtime.deleteLocalUseCaseFromSnapshot(local,uc);assert.deepEqual(local.favoriteUseCaseIds,[])});

test('legacy direct-command favorite IDs migrate to stable semantic card IDs at materialization',()=>{const defs=require('../seed/commands.json').items,pre=defs.find((d)=>d.id==='tmcmd.pre.update');assert.ok(pre);const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:pre,repositoryKnown:true})],favoriteCommandIds:['tmcmd.pre.update']});const memory=runtime.materializeSnapshot(local);assert.deepEqual(memory.favoriteCommandIds,['tm:TM-PRE-UPDATE-PLAN']);const toggled=runtime.toggleFavoriteCommandInSnapshot(local,'tm:TM-PRE-UPDATE-PLAN');assert.deepEqual(toggled.favoriteCommandIds,[])});

test('moveId uses current IDs, preserves unspecified IDs and moves one item',()=>{assert.deepEqual(runtime.moveId(['b'],['a','b','c'],'b',-1),['b','a','c']);assert.deepEqual(runtime.moveId(['a','c'],['a','b','c'],'c',-1),['c','a','b'])});


test('presentation grouping moves one card without changing semantic identity',()=>{
  const order={schemaVersion:2,commands:['a','b'],commandGroups:[{id:'g.one',viewId:'GENERAL',label:'One',order:0,items:['a']},{id:'g.two',viewId:'GENERAL',label:'Two',order:1,items:['b']}]};
  const next=runtime.assignCommandGroupInOrder(order,'a','g.two');
  assert.deepEqual(next.commandGroups.find((group)=>group.id==='g.one').items,[]);
  assert.deepEqual(next.commandGroups.find((group)=>group.id==='g.two').items,['b','a']);
  assert.deepEqual(next.commands,['a','b']);
});



test('presentation groups are one ordered list per tab and support create rename reorder and delete-to-Ungrouped',()=>{
  let order={schemaVersion:4,commands:['a','b'],commandGroups:[{id:'g.one',viewId:'GENERAL',label:'One',order:10,items:['a']},{id:'g.two',viewId:'GENERAL',label:'Two',order:20,items:['b']}]};
  order=runtime.createCommandGroupInOrder(order,{viewId:'GENERAL',label:'Custom Review'});
  const created=order.commandGroups.find((group)=>group.label==='Custom Review');assert.ok(created);assert.equal('level' in created,false);
  order=runtime.updateCommandGroupInOrder(order,created.id,{label:'Custom Audit'});assert.equal(order.commandGroups.find((group)=>group.id===created.id).label,'Custom Audit');
  order=runtime.assignCommandGroupInOrder(order,'a',created.id,'GENERAL');assert.deepEqual(order.commandGroups.find((group)=>group.id===created.id).items,['a']);
  const before=order.commandGroups.filter((group)=>group.viewId==='GENERAL').sort((a,b)=>a.order-b.order).map((group)=>group.id),createdIndex=before.indexOf(created.id);
  order=runtime.moveCommandGroupInOrder(order,created.id,-1);const after=order.commandGroups.filter((group)=>group.viewId==='GENERAL').sort((a,b)=>a.order-b.order).map((group)=>group.id);assert.equal(after.indexOf(created.id),Math.max(0,createdIndex-1));
  order=runtime.deleteCommandGroupInOrder(order,created.id);const fallback=order.commandGroups.find((group)=>group.label==='Other / Ungrouped');assert.ok(fallback);assert.ok(fallback.items.includes('a'));assert.equal(order.commandGroups.some((group)=>group.id===created.id),false);
});

test('runtime hard-reload source is an authoritative command/catalog replace and preserves prompts only',()=>{
  const source=require('node:fs').readFileSync(require('node:path').resolve(import.meta.dirname,'../src/planning-helper-runtime.js'),'utf8');
  assert.match(source,/preservedPrompts=memory\.helperRecords\.filter/);
  assert.match(source,/removedLegacyCommands=memory\.helperRecords\.length-preservedPrompts\.length/);
  assert.match(source,/planningCommands,helperItems:preservedPrompts,useCases:useCaseCatalog\.useCases/);
  assert.match(source,/catalogOrder:order\.order/);
  assert.match(source,/suppressedRepository:\{helperItems:suppressionState\(snapshot\)\.helperItems\},hiddenCommandIds:\[\],hiddenUseCaseIds:\[\]/);
});

test('Planning Helper patch atomically upserts every supported local catalog type',()=>{const local=snapshot(),command=def('patch.command','patch command'),prompt=helperItem('prompt','patch-prompt','patch prompt'),useCase={...currentUseCases[0],id:'UC-PATCH-IMPORT',label:'Patch Import UC',target:'<patch import>'},component={...currentSemanticComponents[0],id:'LENS-PATCH-IMPORT',label:'Patch Import Lens',actionLabel:'Patch Import Lens'},scenario={id:'SCN-PATCH-IMPORT',type:'FOCUSED',title:'Patch import scenario',entryRoute:'local import',assumptions:[],steps:[{id:'SCN-PATCH-IMPORT-S1',title:'Run imported scenario',semanticRefs:['LENS-PATCH-IMPORT']}],canonicalIntro:'Imported scenario',source:'local import'};const patch={schemaVersion:1,upsert:{commands:[command],helperItems:[prompt],useCases:[useCase],semanticComponents:[component],scenarios:[scenario]},delete:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},catalogOrder:null};const merged=runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch},'import'),memory=runtime.materializeSnapshot(merged.snapshot);assert.ok(memory.commandById.has('patch.command'));assert.ok(memory.helperByKey.has('prompt:patch-prompt'));assert.ok(memory.useCases.some((entry)=>entry.id==='UC-PATCH-IMPORT'));assert.ok(memory.semanticComponents.some((entry)=>entry.id==='LENS-PATCH-IMPORT'));assert.ok(memory.scenarios.some((entry)=>entry.id==='SCN-PATCH-IMPORT'));assert.equal(merged.snapshot.useCaseCatalogSha,'');assert.equal(merged.snapshot.semanticComponentCatalogSha,'');assert.equal(merged.snapshot.scenarioCatalogSha,'');assert.match(merged.lines.join('\n'),/ADD planning\/commands\/patch.command.command.md/);assert.match(merged.lines.join('\n'),/ADD scenario SCN-PATCH-IMPORT/)});

test('patch delete suppresses repository restoration until upsert or Hard Reload',()=>{const command=def('suppressed.command','suppressed command'),prompt=helperItem('prompt','suppressed-prompt','x'),useCase={...currentUseCases[0],id:'UC-SUPPRESSED',label:'Suppressed UC',target:'<suppressed>'},component={...currentSemanticComponents[0],id:'LENS-SUPPRESSED',label:'Suppressed Lens',actionLabel:'Suppressed Lens'},scenario={id:'SCN-SUPPRESSED',type:'FOCUSED',title:'Suppressed scenario',entryRoute:'x',assumptions:[],steps:[{id:'SCN-SUPPRESSED-S1',title:'x',semanticRefs:[]}],canonicalIntro:'x',source:'x'};let local=runtime.mergeChatImport(snapshot(),{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[command],helperItems:[prompt],useCases:[useCase],semanticComponents:[component],scenarios:[scenario]},delete:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import').snapshot;const deleted=runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},delete:{commands:['planning/commands/suppressed.command.command.md'],helperItems:['prompt:suppressed-prompt'],useCases:['UC-SUPPRESSED'],semanticComponents:['LENS-SUPPRESSED'],scenarios:['SCN-SUPPRESSED']},catalogOrder:null}},'import').snapshot;assert.deepEqual(deleted.suppressedRepository.commands,['planning/commands/suppressed.command.command.md']);assert.deepEqual(deleted.suppressedRepository.useCases,['UC-SUPPRESSED']);const blocked=runtime.mergeRemoteMissing(deleted,{commands:[{path:'planning/commands/suppressed.command.command.md',sha:'remote',definition:command,rawContent:codec.renderCommandDefinitionDocument(command)}],helperItems:[{path:helper.helperLibraryTargetPath(prompt),sha:'remote',item:prompt,rawContent:helper.renderHelperLibraryDocument(prompt)}],useCases:[useCase],semanticComponents:[component],scenarios:[scenario]});assert.equal(blocked.addedCommands.length,0);assert.equal(blocked.addedHelpers.length,0);assert.equal(blocked.addedUseCases.length,0);assert.equal(blocked.addedSemanticComponents.length,0);assert.equal(blocked.addedScenarios.length,0);const restored=runtime.mergeChatImport(blocked.snapshot,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[scenario]},delete:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import').snapshot;assert.ok(restored.scenarios.some((entry)=>entry.id==='SCN-SUPPRESSED'));assert.equal(restored.suppressedRepository.scenarios.includes('SCN-SUPPRESSED'),false)});

test('invalid patch leaves the input snapshot unchanged because validation happens before persistence',()=>{const local=snapshot(),before=JSON.stringify(local);assert.throws(()=>runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[{id:'bad'}]},delete:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import'));assert.equal(JSON.stringify(local),before)});

test('pasted Restore clears suppression for repository command/helper items it restores',()=>{const command=def('restore-suppressed','restore suppressed'),prompt=helperItem('prompt','restore-suppressed','restore');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[],helperItems:[],suppressedRepository:{commands:[codec.commandPathForDefinition(command)],helperItems:[helper.helperLibraryTargetPath(prompt)]}});const merged=runtime.mergeChatImport(local,{definitions:[command],helperItems:[prompt],patch:null},'restore');assert.equal(merged.snapshot.suppressedRepository.commands.includes(codec.commandPathForDefinition(command)),false);assert.equal(merged.snapshot.suppressedRepository.helperItems.includes(helper.helperLibraryTargetPath(prompt)),false);assert.ok(runtime.materializeSnapshot(merged.snapshot).commandById.has('restore-suppressed'));assert.ok(runtime.materializeSnapshot(merged.snapshot).helperByKey.has('prompt:restore-suppressed'))});


test('Use-Case materialization repairs a missing raw UC semantic component instead of falling through to Lens body',()=>{const id='UC-IDTSPE-COMPOSE-CURRENT-WORK',local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),semanticComponents:currentSemanticComponents.filter((entry)=>entry.id!==id)}),memory=runtime.materializeSnapshot(local),entry=memory.commandEntries.find((item)=>item.canonicalId===id);assert.ok(entry);assert.match(entry.adaptiveBody,/\[PLANNING_USE_CASE\]/);assert.doesNotMatch(entry.adaptiveBody,/lens_id:/)});

test('Use-Case import owns its coupled semantic projection and capability delete hides direct backing',()=>{const id='UC-IDTSPE-COMPOSE-CURRENT-WORK',direct=require('../seed/commands.json').items.find((item)=>item.id==='plan.now');assert.ok(direct);let local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:direct,repositoryKnown:true})]});const deleted=runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},delete:{commands:[],helperItems:[],useCases:[id],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import');assert.ok(deleted.snapshot.suppressedRepository.useCases.includes(id));assert.ok(deleted.snapshot.suppressedRepository.semanticComponents.includes(id));assert.ok(deleted.snapshot.hiddenCommandIds.includes('plan.now'));assert.equal(runtime.materializeSnapshot(deleted.snapshot).commandEntries.some((entry)=>entry.canonicalId===id||entry.id==='plan.now'),false);const useCase=currentUseCases.find((entry)=>entry.id===id),restored=runtime.mergeChatImport(deleted.snapshot,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[useCase],semanticComponents:[],scenarios:[]},delete:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import');assert.equal(restored.snapshot.suppressedRepository.useCases.includes(id),false);assert.equal(restored.snapshot.suppressedRepository.semanticComponents.includes(id),false);assert.equal(restored.snapshot.hiddenCommandIds.includes('plan.now'),true);const rawComponent=restored.snapshot.semanticComponents.find((entry)=>entry.id===id);assert.equal(rawComponent.kind,'USE_CASE');assert.equal(rawComponent.label,useCase.label);const entry=runtime.materializeSnapshot(restored.snapshot).commandEntries.find((item)=>item.canonicalId===id);assert.equal(entry.directCommandId,'');assert.match(entry.adaptiveBody,/\[PLANNING_USE_CASE\]/)});

test('direct command delete mirrors command-file deletion and preview states when semantic capability remains generic',()=>{const id='UC-IDTSPE-COMPOSE-CURRENT-WORK',direct=require('../seed/commands.json').items.find((item)=>item.id==='plan.now'),local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:direct,repositoryKnown:true})]}),merged=runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},delete:{commands:['plan.now'],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import'),entry=runtime.materializeSnapshot(merged.snapshot).commandEntries.find((item)=>item.canonicalId===id);assert.ok(entry);assert.equal(entry.directCommandId,'');assert.match(merged.lines.join('\n'),/semantic card uc:UC-IDTSPE-COMPOSE-CURRENT-WORK remains as generic projection/)});

test('Target Module or Lens capability delete cannot reappear as a General direct command',()=>{const id='TM-PRE-UPDATE-PLAN',direct=require('../seed/commands.json').items.find((item)=>item.methodologyBinding?.targetModuleId===id);assert.ok(direct);const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:direct,repositoryKnown:true})]}),merged=runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},delete:{commands:[],helperItems:[],useCases:[],semanticComponents:[id],scenarios:[]},catalogOrder:null}},'import'),memory=runtime.materializeSnapshot(merged.snapshot);assert.ok(merged.snapshot.hiddenCommandIds.includes(direct.id));assert.equal(memory.commandEntries.some((entry)=>entry.canonicalId===id||entry.id===direct.id),false)});

test('Import rejects UC semantic-component edits plus duplicate and conflicting operations',()=>{const local=snapshot(),ucComponent=currentSemanticComponents.find((item)=>item.kind==='USE_CASE'),scenario=currentScenarios[0],useCase=currentUseCases[0];assert.throws(()=>runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[],semanticComponents:[ucComponent],scenarios:[]},delete:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import'),/Import Use Cases through upsert\.useCases/);assert.throws(()=>runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[scenario,scenario]},delete:{commands:[],helperItems:[],useCases:[],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import'),/Duplicate Scenario upsert id/);assert.throws(()=>runtime.mergeChatImport(local,{definitions:[],helperItems:[],patch:{schemaVersion:1,upsert:{commands:[],helperItems:[],useCases:[useCase],semanticComponents:[],scenarios:[]},delete:{commands:[],helperItems:[],useCases:[useCase.id],semanticComponents:[],scenarios:[]},catalogOrder:null}},'import'),/cannot be both upserted and deleted/)});
