import test from 'node:test';import assert from 'node:assert/strict';import fs from'node:fs';import path from'node:path';import{fileURLToPath}from'node:url';import{createRequire}from'node:module';const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const repo=path.resolve(root,'../../../../..');const require=createRequire(import.meta.url);const command=require('../src/command-definition-codec.js');const catalog=require('../src/command-catalog.js');const helper=require('../src/helper-library-codec.js');Object.assign(globalThis,{ObsPlanningHelper:{...command,...catalog,...helper}});const state=require('../src/planning-helper-state.js');
test('generated userscript keeps only the GM grants needed for local storage, clipboard DOM and create-only GitHub PUT',()=>{const text=fs.readFileSync(path.resolve(root,'..','chat-command-palette.user.js'),'utf8');assert.match(text,/GENERATED FILE — DO NOT EDIT MANUALLY/);assert.match(text,/@grant\s+GM_getValue/);assert.match(text,/@grant\s+GM_setValue/);assert.match(text,/@grant\s+GM_xmlhttpRequest/);assert.match(text,/@connect\s+api\.github\.com/)});
test('runtime has no GitHub refresh/read/sync path',()=>{const runtime=fs.readFileSync(path.join(root,'src','planning-helper-runtime.js'),'utf8');assert.doesNotMatch(runtime,/\.read\s*\(/);assert.doesNotMatch(runtime,/\.listDirectory\s*\(/);assert.doesNotMatch(runtime,/saveVerified|loadCatalog|syncAll|Refresh repo|Refetch/);assert.match(runtime,/createOnlyBatch/)});
test('repository services are create-only and never read or list',()=>{for(const name of['repository-command-service.js','repository-helper-library-service.js']){const text=fs.readFileSync(path.join(root,'src',name),'utf8');assert.match(text,/\.create\s*\(/);assert.doesNotMatch(text,/\.read\s*\(|\.listDirectory\s*\(|\.write\s*\(|saveVerified|baseSha/);}});
test('GitHub client itself has no GET/read/list/update/read-back capability',()=>{const text=fs.readFileSync(path.join(root,'src','github-contents-client.js'),'utf8');assert.match(text,/async create\s*\(/);assert.doesNotMatch(text,/async read\s*\(|listDirectory|saveVerified|base64ToUtf8/);assert.doesNotMatch(text,/method:'GET'|method:\s*\"GET\"/);});
test('UI exposes ChatGPT recovery and no repository refresh/update controls',()=>{const ui=fs.readFileSync(path.join(root,'src','planning-helper-ui.js'),'utf8');assert.match(ui,/Import from ChatGPT/);assert.match(ui,/Restore from GitHub copy/);assert.match(ui,/Copy recovery request/);assert.match(ui,/create-only GitHub PUT/);assert.doesNotMatch(ui,/Refresh repo|Refresh repo library|Save to GitHub|Repo<|repo-library/)});
test('local snapshot is one v2 GM key and settings do not source-bind it',()=>{assert.equal(state.PLANNING_HELPER_STATE_KEYS.localSnapshot,'obsPlanningHelper:v2:localSnapshot');assert.equal(state.LOCAL_SNAPSHOT_SCHEMA_VERSION,1);const source=fs.readFileSync(path.join(root,'src','planning-helper-state.js'),'utf8');assert.match(source,/typeof GM_getValue==='function'/);assert.match(source,/typeof GM_setValue==='function'/);assert.doesNotMatch(source,/repositorySourceKey/)});
test('command registry verification remains dynamic and build-time authority stays planning commands',()=>{const files=fs.readdirSync(path.join(repo,'planning','commands')).filter((name)=>name.endsWith('.command.md'));assert.ok(files.length>0);const verifier=fs.readFileSync(path.join(root,'verify-chat-command-palette.mjs'),'utf8');assert.doesNotMatch(verifier,/defs\.length\s*!==\s*15|exactly 15/i)});
test('helper codec retains bounded repository backup paths and mixed recovery parser',()=>{const source=fs.readFileSync(path.join(root,'src','helper-library-codec.js'),'utf8');assert.match(source,/planning\/helper-library/);assert.match(source,/\.helper-command\.md/);assert.match(source,/\.prompt\.md/);assert.match(source,/parseHelperLibraryBatch/)});
