import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const codec=require('../src/command-definition-codec.js');
const catalog=require('../src/command-catalog.js');
const helper=require('../src/helper-library-codec.js');
const body=require('../src/command-body.js');
const semantic=require('../src/semantic-projections.js');
const repositoryCatalog=require('../src/repository-catalog-service.js');
const currentDirections=semantic.normalizeDirectionDefinitions(require('../seed/directions.json').items);
const currentUseCases=semantic.normalizeUseCaseDefinitions(require('../seed/use-cases.json').items);
globalThis.ObsPlanningHelper=Object.assign({},codec,catalog,helper,body,semantic,repositoryCatalog);
const state=require('../src/planning-helper-state.js');
Object.assign(globalThis.ObsPlanningHelper,state);
const runtime=require('../src/planning-helper-runtime.js');
function def(id='a',command=id,directionIds=['DIR-REPOSITORY']){return codec.normalizeCommandDefinition({schemaVersion:1,id,file:`${id}.command.md`,command,englishName:`${id} english`,commandFamily:[command],description:'desc',meaning:'meaning',activeContextBehavior:'active',traversalReadMode:'targeted',ownerFiles:[],expectedOutput:'output',permissionMode:'read-only',keyReminders:['remember'],userTarget:'<target>',palette:true,directionIds,refinements:[]})}
function helperItem(kind,id,text='text'){return helper.normalizeHelperLibraryItem({kind,id,title:`${kind} ${id}`,text,createdAt:'2026-08-16T00:00:00Z',updatedAt:'2026-08-16T00:00:00Z'})}
function snapshot(){const a=def('a'),hc=helperItem('command','hc'),p=helperItem('prompt','p');return state.normalizePlanningHelperLocalSnapshot({schemaVersion:4,savedAt:'2026-08-16T00:00:00Z',planningCommands:[state.normalizeCommandRecord({definition:a,repositoryKnown:true,repositorySha:'sha-a'})],helperItems:[state.normalizeHelperRecord({item:hc,repositoryKnown:false}),state.normalizeHelperRecord({item:p,repositoryKnown:true,repositorySha:'sha-p'})],directions:currentDirections,directionCatalogSha:'dir-sha',useCases:currentUseCases,useCaseCatalogSha:'uc-sha',catalogOrder:{}})}

test('repository inventory compares commands, Directions, Use Cases and prompts without fetching bodies',()=>{const local=snapshot();const inventory=runtime.compareRepositoryInventory(local,{commands:[{kind:'planning-command',path:'planning/commands/a.command.md',sha:'sha-a'},{kind:'planning-command',path:'planning/commands/b.command.md',sha:'sha-b'}],directions:currentDirections,directionSha:'dir-sha',useCases:currentUseCases,useCaseSha:'uc-sha',helperItems:[{kind:'command',path:'planning/helper-library/commands/remote.helper-command.md',sha:'x'},{kind:'prompt',path:'planning/helper-library/prompts/p.prompt.md',sha:'sha-p'}]});assert.equal(inventory.planningCommands.local,1);assert.equal(inventory.planningCommands.remote,2);assert.deepEqual(inventory.planningCommands.remoteOnly,['planning/commands/b.command.md']);assert.equal(inventory.directions.common,currentDirections.length);assert.equal(inventory.useCases.common,currentUseCases.length);assert.deepEqual(inventory.helperCommands.localOnly,['planning/helper-library/commands/hc.helper-command.md']);assert.equal(inventory.prompts.common,1)});

test('repository inventory reports known catalog SHA changes',()=>{const inventory=runtime.compareRepositoryInventory(snapshot(),{commands:[{kind:'planning-command',path:'planning/commands/a.command.md',sha:'changed'}],directions:currentDirections,directionSha:'new-dir',useCases:currentUseCases,useCaseSha:'new-uc',helperItems:[{kind:'prompt',path:'planning/helper-library/prompts/p.prompt.md',sha:'sha-p'}]});assert.deepEqual(inventory.planningCommands.knownChanged,['planning/commands/a.command.md']);assert.deepEqual(inventory.directions.knownChanged,['seed/directions.json']);assert.deepEqual(inventory.useCases.knownChanged,['seed/use-cases.json'])});

test('sync merge adds only missing repository records and never overwrites same-path/same-id local records',()=>{const local=snapshot(),b=def('b'),remotePrompt=helperItem('prompt','remote','remote text'),newDirection={id:'DIR-NEW',label:'New',description:'new',sources:['planning/direction-registry.md']},newUc={id:'UC-NEW',label:'New UC',description:'new',sources:['planning/use-case-registry.md'],instruction:'Resolve current owner.',target:'<new>',directionId:'DIR-NEW',manualInvocation:true,trigger:'x',result:'y'};const merged=runtime.mergeRemoteMissing(local,{commands:[{path:'planning/commands/a.command.md',sha:'remote-a',definition:{...def('a'),description:'REMOTE SHOULD NOT WIN'},rawContent:codec.renderCommandDefinitionDocument({...def('a'),description:'REMOTE SHOULD NOT WIN'})},{path:'planning/commands/b.command.md',sha:'sha-b',definition:b,rawContent:codec.renderCommandDefinitionDocument(b)}],helperItems:[{path:helper.helperLibraryTargetPath(remotePrompt),sha:'sha-r',item:remotePrompt,rawContent:helper.renderHelperLibraryDocument(remotePrompt)}],directions:[newDirection],useCases:[newUc]});const materialized=runtime.materializeSnapshot(merged.snapshot);assert.equal(materialized.commandById.get('a').definition.description,'desc');assert.ok(materialized.commandById.has('b'));assert.ok(materialized.helperByKey.has('prompt:remote'));assert.ok(materialized.directions.some((d)=>d.id==='DIR-NEW'));assert.ok(materialized.useCases.some((u)=>u.id==='UC-NEW'));assert.equal(merged.addedCommands.length,1);assert.equal(merged.addedHelpers.length,1);assert.equal(merged.addedDirections.length,1);assert.equal(merged.addedUseCases.length,1)});

test('invocation preparation awaits command side effects only at action time',async()=>{const calls=[];const bodyText=await runtime.prepareInvocationBody('BASE','replacement_archive.create',{async applyCommandSideEffects(id,text){calls.push([id,text]);return `${text}\n\nSIDE`;}});assert.equal(bodyText,'BASE\n\nSIDE');assert.deepEqual(calls,[['replacement_archive.create','BASE']]);});

test('clipboard/composer insertion path remains network-agnostic',async()=>{const calls=[];const message=await runtime.insertWithClipboard('BODY','Inserted','cmd',{copyText(text){calls.push(['copy',text]);return true},insertIntoComposer(text,id){calls.push(['insert',text,id]);return{ok:true}}});assert.match(message,/clipboard ready/);assert.deepEqual(calls,[['copy','BODY'],['insert','BODY','cmd']])});

test('local command import/edit clears exact repository evidence only when bytes change',()=>{const original=def('repo-cmd','repo cmd');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:original,repositoryKnown:true,repositorySha:'remote-sha'})]});const changed={...original,description:'locally changed'};const changedMerge=runtime.mergeChatImport(local,{definitions:[changed],helperItems:[]},'import');assert.equal(changedMerge.snapshot.planningCommands[0].repositoryKnown,false);assert.equal(changedMerge.snapshot.planningCommands[0].repositorySha,'');const sameMerge=runtime.mergeChatImport(local,{definitions:[original],helperItems:[]},'import');assert.equal(sameMerge.snapshot.planningCommands[0].repositoryKnown,true);assert.equal(sameMerge.snapshot.planningCommands[0].repositorySha,'remote-sha')});

test('local helper save preserves evidence on no-op and clears it on edit',()=>{const item=helperItem('prompt','same','text');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[],helperItems:[state.normalizeHelperRecord({item,repositoryKnown:true,repositorySha:'sha-1'})]});const unchanged=runtime.prepareLocalHelperSave(local,{kind:'prompt',id:'same',title:item.title,text:item.text,createdAt:item.createdAt},'2026-08-17T00:00:00Z');assert.equal(unchanged.changed,false);assert.equal(unchanged.record.repositorySha,'sha-1');const changed=runtime.prepareLocalHelperSave(local,{kind:'prompt',id:'same',title:item.title,text:'new',createdAt:item.createdAt},'2026-08-17T00:00:00Z');assert.equal(changed.changed,true);assert.equal(changed.record.repositoryKnown,false);assert.equal(changed.record.repositorySha,'')});

test('verified remote result remains success when only local evidence persistence fails',async()=>{const result=await runtime.persistVerifiedRepositoryResult(async()=>{throw new Error('quota')},{},{ok:true,action:'update',path:'x',sha:'remote-sha'},{owner:'o',repo:'r',branch:'main'},()=>({promptEntries:['old']}));assert.equal(result.ok,true);assert.equal(result.sha,'remote-sha');assert.equal(result.localSnapshotUpdated,false);assert.match(result.localSnapshotError,/quota/)});

test('repository source change clears exact repository evidence but keeps local data',()=>{const cleared=runtime.clearRepositoryEvidence(snapshot());assert.equal(cleared.planningCommands[0].definition.id,'a');assert.equal(cleared.planningCommands[0].repositoryKnown,false);assert.equal(cleared.helperItems.length,2);assert.equal(cleared.directionCatalogSha,'');assert.equal(cleared.useCaseCatalogSha,'');assert.equal(cleared.catalogOrderSha,'')});

test('restore reconciles repository-backed records but preserves local-only content without inventing SHA',()=>{const remoteOld=def('remote-old','remote old'),remoteKeep=def('remote-keep','remote keep'),localOnly=helperItem('prompt','local-only','keep me');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:remoteOld,repositoryKnown:true,repositorySha:'old-sha'})],helperItems:[state.normalizeHelperRecord({item:localOnly,repositoryKnown:false})]});const merged=runtime.mergeChatImport(local,{definitions:[remoteKeep],helperItems:[]},'restore');assert.equal(merged.removedRepositoryCommands,1);assert.equal(merged.snapshot.planningCommands[0].definition.id,'remote-keep');assert.equal(merged.snapshot.planningCommands[0].repositorySha,'');assert.equal(merged.snapshot.helperItems[0].item.id,'local-only')});

test('planning command draft edit preserves tracked provenance and cannot rename id/file in place',()=>{const original=def('tracked','tracked');const local=state.normalizePlanningHelperLocalSnapshot({...snapshot(),planningCommands:[state.normalizeCommandRecord({definition:original,repositoryKnown:true,repositoryTracked:true,repositorySha:'sha'})]});const changed={...original,description:'changed locally'};const prepared=runtime.prepareLocalCommandSave(local,changed,'tracked');assert.equal(prepared.record.repositoryKnown,false);assert.equal(prepared.record.repositoryTracked,true);assert.equal(prepared.record.repositorySha,'');assert.throws(()=>runtime.prepareLocalCommandSave(local,{...original,id:'renamed',file:'renamed.command.md'},'tracked'),/cannot change its id or file/)});

test('local Delete hides/removes catalog rows and explicit sync can restore a deleted command',()=>{const local=snapshot();const deleted=runtime.deleteLocalCommandFromSnapshot(local,'a');assert.equal(deleted.planningCommands.some((r)=>r.definition.id==='a'),false);assert.deepEqual(deleted.hiddenCommandIds,['a']);const definition=def('a');const merged=runtime.mergeRemoteMissing(deleted,{commands:[{path:'planning/commands/a.command.md',sha:'fresh',definition,rawContent:codec.renderCommandDefinitionDocument(definition)}]});assert.equal(merged.snapshot.planningCommands.some((r)=>r.definition.id==='a'),true);assert.deepEqual(merged.snapshot.hiddenCommandIds,[])});

test('local Use-Case hide does not alter repository-backed semantic catalog',()=>{const local=snapshot(),id='UC-PLAN-DOMAIN';assert.ok(currentUseCases.some((u)=>u.id===id));const next=runtime.deleteLocalUseCaseFromSnapshot(local,id);assert.ok(next.hiddenUseCaseIds.includes(id));assert.equal(runtime.materializeSnapshot(next).useCaseEntries.some((e)=>e.id===id),false);assert.ok(next.useCases.some((u)=>u.id===id))});

test('every current UC has exactly one manual command route: bespoke or generated',()=>{const memory=runtime.materializeSnapshot(snapshot());for(const uc of currentUseCases){const bespoke=uc.commandId?memory.commandEntries.filter((e)=>e.id===uc.commandId):[];const generated=memory.commandEntries.filter((e)=>e.entityType==='use-case-invocation-command'&&e.useCaseId===uc.id);assert.equal(bespoke.length+generated.length,1,uc.id)}});

test('generated UC invocation can be hidden without hiding its Use Case',()=>{const local=snapshot(),generated=runtime.materializeSnapshot(local).commandEntries.find((e)=>e.entityType==='use-case-invocation-command');assert.ok(generated);const next=runtime.deleteLocalCommandFromSnapshot(local,generated.id),after=runtime.materializeSnapshot(next);assert.equal(after.commandEntries.some((e)=>e.id===generated.id),false);assert.equal(after.useCaseEntries.some((e)=>e.id===generated.useCaseId),true)});

test('Favorites are local stable-ID projections',()=>{let local=snapshot();local=runtime.toggleFavoriteCommandInSnapshot(local,'a');assert.deepEqual(local.favoriteCommandIds,['a']);const uc='UC-PLAN-DOMAIN';local=runtime.toggleFavoriteUseCaseInSnapshot(local,uc);assert.deepEqual(local.favoriteUseCaseIds,[uc]);local=runtime.deleteLocalUseCaseFromSnapshot(local,uc);assert.deepEqual(local.favoriteUseCaseIds,[])});

test('moveId uses current IDs, preserves unspecified IDs and moves one item',()=>{assert.deepEqual(runtime.moveId(['b'],['a','b','c'],'b',-1),['b','a','c']);assert.deepEqual(runtime.moveId(['a','c'],['a','b','c'],'c',-1),['c','a','b'])});
