import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=(rel)=>fs.readFileSync(path.join(root,rel),'utf8');

test('normal local insert/edit/reorder path stays local and repository access is explicit',()=>{const runtime=read('src/planning-helper-runtime.js');const insert=runtime.slice(runtime.indexOf('async function insertWithClipboard'),runtime.indexOf('async function startPlanningHelper'));assert.doesNotMatch(insert,/GitHub|makeClient|makeServices/);assert.match(runtime,/async function reloadRepositoryCommand\(id\)/);assert.match(runtime,/async function checkRepository\(\)/);assert.match(runtime,/async function syncMissingRepository\(\)/);assert.match(runtime,/async function hardReloadRepository\(\)/);assert.match(runtime,/async function moveCatalogItem/);assert.match(runtime,/async function saveCatalogOrderRepository\(\)/)});

test('UI exposes command-centric Commands/Scenarios/Prompts plus explicit GitHub recovery/order actions',()=>{const ui=read('src/planning-helper-ui.js'),semantic=read('src/semantic-projections.js');assert.match(semantic,/COMMANDS:'Commands',SCENARIOS:'Scenarios',PROMPTS:'Prompts'/);assert.doesNotMatch(semantic,/Direction|directionId|directionIds/);assert.match(ui,/SURFACES\.COMMANDS,SURFACES\.SCENARIOS,SURFACES\.PROMPTS/);assert.match(ui,/★ Favorite/);assert.match(ui,/function renderGroupNavigator/);assert.match(ui,/function renderCommandDetail/);assert.match(ui,/Hard Reload GitHub/);assert.match(ui,/Save order GitHub/);assert.match(ui,/Check GitHub/);assert.match(ui,/Sync missing/);assert.match(ui,/Save GitHub/);assert.match(ui,/onMoveCatalogItem/);assert.doesNotMatch(ui,/onMoveDirection|groupEntriesByDirections/);assert.match(ui,/resize:both/);assert.match(ui,/Math\.min\(980/);assert.match(ui,/minmax\(420px,1fr\)/);assert.match(ui,/GitHub token — used only by explicit GitHub actions/);assert.match(ui,/Normal search\/insert\/copy\/edit\/reorder is local-only/)});

test('GitHub client supports explicit read/list/save with exact read-back and safe conflict recovery',()=>{const client=read('src/github-contents-client.js');assert.match(client,/async listDirectory/);assert.match(client,/async read\(path\)/);assert.match(client,/async saveVerified/);assert.match(client,/read-back content does not match/);assert.match(client,/recoveredAfterConflict/);assert.match(client,/nothing was overwritten/)});

test('composer insertion remains direct Range insertion',()=>{const source=read('src/composer-insertion.js');assert.match(source,/range\.insertNode\(node\)/);assert.doesNotMatch(source,/execCommand\('insertText'/)});

test('UI inventory/conflict messaging distinguishes remote failure from verified-write local-persistence warning',()=>{const ui=read('src/planning-helper-ui.js');assert.match(ui,/current remote content could not be verified/);assert.match(ui,/nothing was overwritten/);assert.match(ui,/repositorySaveFailureMessage/);assert.match(ui,/succeeded, but local snapshot refresh failed/);assert.doesNotMatch(ui,/Directions/);assert.match(ui,/Semantic component projection/);assert.match(ui,/Canonical scenario projection/);assert.match(ui,/Catalog order changed/)});

test('repository source changes clear old-source evidence before new settings become active',()=>{const runtime=read('src/planning-helper-runtime.js');const start=runtime.indexOf('async function saveSettings(settings,token)'),end=runtime.indexOf('const ui=deps.createPlanningHelperUi',start),body=runtime.slice(start,end);const clear=body.indexOf('persist(clearRepositoryEvidence(snapshot))'),token=body.indexOf('saveGitHubToken(token)'),settings=body.indexOf('saveRepositorySettings(candidate)');assert.ok(clear>=0&&token>clear&&settings>token)});
