import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const commandCodec=require('../src/command-definition-codec.js');
const catalog=require('../src/command-catalog.js');
const helper=require('../src/helper-library-codec.js');
const semantic=require('../src/semantic-projections.js');
const repositoryCatalog=require('../src/repository-catalog-service.js');
Object.assign(globalThis,{ObsPlanningHelper:{...commandCodec,...catalog,...helper,...semantic,...repositoryCatalog}});
const state=require('../src/planning-helper-state.js');
const def=commandCodec.normalizeCommandDefinition({schemaVersion:1,id:'demo.create',file:'demo.command.md',command:'demo',englishName:'demo',commandFamily:['demo'],description:'d',meaning:'m',activeContextBehavior:'a',traversalReadMode:'t',ownerFiles:[],expectedOutput:'o',permissionMode:'read-only',keyReminders:['r'],userTarget:'<t>',palette:true,refinements:[]});
const prompt=helper.normalizeHelperLibraryItem({kind:'prompt',id:'p',title:'P',text:'prompt',createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z'});
async function withGm(initial,fn){const oldGet=globalThis.GM_getValue,oldSet=globalThis.GM_setValue;const values=new Map(Object.entries(initial||{}));let gets=0,sets=0;globalThis.GM_getValue=async(key,fallback)=>{gets++;return values.has(key)?values.get(key):fallback};globalThis.GM_setValue=async(key,value)=>{sets++;values.set(key,value)};try{return await fn(values,()=>({gets,sets}))}finally{if(oldGet===undefined)delete globalThis.GM_getValue;else globalThis.GM_getValue=oldGet;if(oldSet===undefined)delete globalThis.GM_setValue;else globalThis.GM_setValue=oldSet;}}

test('unified local snapshot v5 stores command/helper raw text plus repository-backed catalog fields',async()=>withGm({},async()=>{const saved=await state.savePlanningHelperLocalSnapshot({schemaVersion:5,planningCommands:[{definition:def,repositoryKnown:true}],helperItems:[{item:prompt,repositoryKnown:false}],useCases:[],catalogOrder:{commands:['demo.create']}});assert.equal(saved.schemaVersion,5);assert.ok(saved.planningCommands[0].rawContent.includes('[PLANNING_COMMAND_DEFINITION]'));assert.ok(saved.helperItems[0].rawContent.includes('[PLANNING_HELPER_LIBRARY_ITEM]'));assert.deepEqual(saved.catalogOrder.commands,['demo.create']);const loaded=await state.loadPlanningHelperLocalSnapshot();assert.equal(loaded.planningCommands[0].definition.id,'demo.create');assert.equal(loaded.helperItems[0].item.text,'prompt')}));

test('warm v5 snapshot load is one GM read and never silently fetches or injects bundled catalogs',async()=>{const payload=state.normalizePlanningHelperLocalSnapshot({schemaVersion:5,savedAt:'2026-01-01T00:00:00Z',planningCommands:[{definition:def,repositoryKnown:true}],helperItems:[],useCases:[],catalogOrder:{},hiddenCommandIds:['hidden.command']});await withGm({[state.PLANNING_HELPER_STATE_KEYS.localSnapshot]:payload},async(_values,counters)=>{const result=await state.loadOrMigratePlanningHelperLocalSnapshot();assert.equal(result.migrated,false);assert.equal(result.seededCommands,0);assert.deepEqual(result.snapshot.planningCommands.map((r)=>r.definition.id),['demo.create']);assert.deepEqual(result.snapshot.hiddenCommandIds,['hidden.command']);assert.equal(counters().gets,1)})});

test('legacy caches migrate locally without GitHub and preserve repository-known helper status',async()=>{const repoRecord={item:prompt,path:helper.helperLibraryTargetPath(prompt),sha:'abc',fetchedAt:'2026-01-01T00:00:00Z'},local={...prompt,text:'local override',updatedAt:'2026-02-01T00:00:00Z'},initial={[state.PLANNING_HELPER_LEGACY_STATE_KEYS.commandCache]:{schemaVersion:1,definitions:[def]},[state.PLANNING_HELPER_LEGACY_STATE_KEYS.repositoryLibraryCache]:{schemaVersion:2,records:[repoRecord]},[state.PLANNING_HELPER_LEGACY_STATE_KEYS.localLibrary]:{schemaVersion:1,items:[local]}};await withGm(initial,async()=>{const result=await state.loadOrMigratePlanningHelperLocalSnapshot();assert.equal(result.migrated,true);assert.equal(result.snapshot.schemaVersion,5);assert.equal(result.snapshot.helperItems[0].item.text,'local override');assert.equal(result.snapshot.helperItems[0].repositoryKnown,true);assert.equal(result.snapshot.helperItems[0].repositorySha,'abc');assert.deepEqual(result.snapshot.useCases,[]);assert.match(result.warnings.join('\n'),/Hard Reload GitHub/)})});

test('repository settings do not bind or delete local snapshot',async()=>withGm({},async()=>{await state.savePlanningHelperLocalSnapshot({schemaVersion:5,planningCommands:[{definition:def,repositoryKnown:true}],helperItems:[],useCases:[],catalogOrder:{}});await state.saveRepositorySettings({owner:'Other',repo:'Else',branch:'dev'});const loaded=await state.loadPlanningHelperLocalSnapshot();assert.equal(loaded.planningCommands[0].definition.id,'demo.create')}));

test('direct repository SHA always implies repository evidence even if legacy flag is false',()=>{const commandRecord=state.normalizeCommandRecord({definition:def,repositoryKnown:false,repositorySha:'sha-direct'}),helperRecord=state.normalizeHelperRecord({item:prompt,repositoryKnown:false,repositorySha:'sha-helper'});assert.equal(commandRecord.repositoryKnown,true);assert.equal(commandRecord.repositoryTracked,true);assert.equal(helperRecord.repositoryKnown,true)});

test('schema-1 snapshot migrates to schema 5 without losing content and initializes new catalog fields',async()=>{const legacy={schemaVersion:1,savedAt:'2026-01-01T00:00:00Z',planningCommands:[{definition:def,repositoryKnown:true}],helperItems:[]};await withGm({[state.PLANNING_HELPER_STATE_KEYS.localSnapshot]:legacy},async()=>{const result=await state.loadOrMigratePlanningHelperLocalSnapshot();assert.equal(result.migrated,true);assert.equal(result.snapshot.schemaVersion,5);assert.deepEqual(result.snapshot.hiddenCommandIds,[]);assert.deepEqual(result.snapshot.hiddenUseCaseIds,[]);assert.deepEqual(result.snapshot.favoriteCommandIds,[]);assert.deepEqual(result.snapshot.favoriteUseCaseIds,[]);assert.deepEqual(result.snapshot.useCases,[]);assert.deepEqual(result.snapshot.catalogOrder.commands,[])})});

test('schema-2/3 snapshots migrate to schema 5 with local tombstones/favorites preserved',async()=>{for(const version of [2,3]){const legacy={schemaVersion:version,savedAt:'2026-01-01T00:00:00Z',planningCommands:[{definition:def,repositoryKnown:true}],helperItems:[],hiddenCommandIds:['hidden'],hiddenUseCaseIds:['UC-X'],favoriteCommandIds:version===3?['demo.create']:[],favoriteUseCaseIds:version===3?['UC-X']:[]};await withGm({[state.PLANNING_HELPER_STATE_KEYS.localSnapshot]:legacy},async()=>{const result=await state.loadOrMigratePlanningHelperLocalSnapshot();assert.equal(result.snapshot.schemaVersion,5);assert.deepEqual(result.snapshot.hiddenCommandIds,['hidden']);assert.deepEqual(result.snapshot.hiddenUseCaseIds,['UC-X']);assert.deepEqual(result.snapshot.favoriteCommandIds,version===3?['demo.create']:[])})}});

test('legacy schema-4 snapshot drops retired Direction placement from command definitions',async()=>{const legacyDef={...def,directionIds:['DIR-REPOSITORY']};const legacy={schemaVersion:4,savedAt:'2026-01-01T00:00:00Z',planningCommands:[{definition:legacyDef,repositoryKnown:true}],helperItems:[],useCases:[],catalogOrder:{}};await withGm({[state.PLANNING_HELPER_STATE_KEYS.localSnapshot]:legacy},async()=>{const result=await state.loadOrMigratePlanningHelperLocalSnapshot();assert.equal(result.snapshot.schemaVersion,5);assert.equal('directionIds' in result.snapshot.planningCommands[0].definition,false)})});

test('panel geometry persists width and height in addition to position',()=>{const old=globalThis.localStorage;const map=new Map();globalThis.localStorage={getItem:(k)=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};try{state.savePanelPosition({left:10,top:20,width:900,height:700});assert.deepEqual(state.readPanelPosition(),{left:10,top:20,width:900,height:700})}finally{if(old===undefined)delete globalThis.localStorage;else globalThis.localStorage=old}});
