import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const codec=require('../src/command-definition-codec.js');
const catalog=require('../src/command-catalog.js');
const helper=require('../src/helper-library-codec.js');
const body=require('../src/command-body.js');
const semantic=require('../src/semantic-projections.js');
globalThis.ObsPlanningHelper=Object.assign({},codec,catalog,helper,body,semantic);
const state=require('../src/planning-helper-state.js');
Object.assign(globalThis.ObsPlanningHelper,state);
const runtime=require('../src/planning-helper-runtime.js');
function def(id='a',command=id){return codec.normalizeCommandDefinition({schemaVersion:1,id,file:`${id}.command.md`,command,englishName:`${id} english`,commandFamily:[command],description:'desc',meaning:'meaning',activeContextBehavior:'active',traversalReadMode:'targeted',ownerFiles:[],expectedOutput:'output',permissionMode:'read-only',keyReminders:['remember'],userTarget:'<target>',palette:true,refinements:[]})}
function helperItem(kind,id,text='text'){return helper.normalizeHelperLibraryItem({kind,id,title:`${kind} ${id}`,text,createdAt:'2026-08-16T00:00:00Z',updatedAt:'2026-08-16T00:00:00Z'})}
function snapshot(){const a=def('a'),hc=helperItem('command','hc'),p=helperItem('prompt','p');return state.normalizePlanningHelperLocalSnapshot({schemaVersion:1,savedAt:'2026-08-16T00:00:00Z',planningCommands:[state.normalizeCommandRecord({definition:a,repositoryKnown:true,repositorySha:'sha-a'})],helperItems:[state.normalizeHelperRecord({item:hc,repositoryKnown:false}),state.normalizeHelperRecord({item:p,repositoryKnown:true,repositorySha:'sha-p'})]})}

test('repository inventory compares local/GitHub counts and path names without fetching bodies',()=>{const local=snapshot();const inventory=runtime.compareRepositoryInventory(local,{commands:[{kind:'planning-command',path:'planning/commands/a.command.md',sha:'sha-a'},{kind:'planning-command',path:'planning/commands/b.command.md',sha:'sha-b'}],helperItems:[{kind:'command',path:'planning/helper-library/commands/remote.helper-command.md',sha:'x'},{kind:'prompt',path:'planning/helper-library/prompts/p.prompt.md',sha:'sha-p'}]});assert.equal(inventory.planningCommands.local,1);assert.equal(inventory.planningCommands.remote,2);assert.deepEqual(inventory.planningCommands.remoteOnly,['planning/commands/b.command.md']);assert.deepEqual(inventory.helperCommands.localOnly,['planning/helper-library/commands/hc.helper-command.md']);assert.equal(inventory.prompts.common,1)});

test('repository inventory reports a changed known remote SHA but does not infer content equality from names alone',()=>{const inventory=runtime.compareRepositoryInventory(snapshot(),{commands:[{kind:'planning-command',path:'planning/commands/a.command.md',sha:'changed'}],helperItems:[{kind:'prompt',path:'planning/helper-library/prompts/p.prompt.md',sha:'sha-p'}]});assert.deepEqual(inventory.planningCommands.knownChanged,['planning/commands/a.command.md']);assert.deepEqual(inventory.prompts.knownChanged,[])});

test('sync merge adds only GitHub-only records and never overwrites same-path local records',()=>{const local=snapshot(),b=def('b'),remotePrompt=helperItem('prompt','remote','remote text');const merged=runtime.mergeRemoteMissing(local,{commands:[{path:'planning/commands/a.command.md',sha:'remote-a',definition:{...def('a'),description:'REMOTE SHOULD NOT WIN'},rawContent:codec.renderCommandDefinitionDocument({...def('a'),description:'REMOTE SHOULD NOT WIN'})},{path:'planning/commands/b.command.md',sha:'sha-b',definition:b,rawContent:codec.renderCommandDefinitionDocument(b)}],helperItems:[{path:helper.helperLibraryTargetPath(remotePrompt),sha:'sha-r',item:remotePrompt,rawContent:helper.renderHelperLibraryDocument(remotePrompt)}]});const materialized=runtime.materializeSnapshot(merged.snapshot);assert.equal(materialized.commandById.get('a').definition.description,'desc');assert.ok(materialized.commandById.has('b'));assert.ok(materialized.helperByKey.has('prompt:remote'));assert.equal(merged.addedCommands.length,1);assert.equal(merged.addedHelpers.length,1)});

test('clipboard/composer insertion path remains network-agnostic and does not touch repository operations',async()=>{const calls=[];const message=await runtime.insertWithClipboard('BODY','Inserted','cmd',{copyText(text){calls.push(['copy',text]);return true},insertIntoComposer(text,id){calls.push(['insert',text,id]);return{ok:true}}});assert.match(message,/clipboard ready/);assert.deepEqual(calls,[['copy','BODY'],['insert','BODY','cmd']])});

test('local import clears repository verification metadata when an existing record changes',()=>{const original=def('repo-cmd','repo cmd');const local=state.normalizePlanningHelperLocalSnapshot({schemaVersion:1,savedAt:'2026-08-16T00:00:00Z',planningCommands:[state.normalizeCommandRecord({definition:original,repositoryKnown:true,repositorySha:'remote-sha'})],helperItems:[]});const changed={...original,description:'locally changed'};const merged=runtime.mergeChatImport(local,{definitions:[changed],helperItems:[]},'import');assert.equal(merged.snapshot.planningCommands[0].repositoryKnown,false);assert.equal(merged.snapshot.planningCommands[0].repositorySha,'')});

test('local import preserves repository verification metadata when exact rendered bytes are unchanged',()=>{const original=def('repo-same','repo same');const local=state.normalizePlanningHelperLocalSnapshot({schemaVersion:1,savedAt:'2026-08-16T00:00:00Z',planningCommands:[state.normalizeCommandRecord({definition:original,repositoryKnown:true,repositorySha:'remote-sha'})],helperItems:[]});const merged=runtime.mergeChatImport(local,{definitions:[original],helperItems:[]},'import');assert.equal(merged.snapshot.planningCommands[0].repositoryKnown,true);assert.equal(merged.snapshot.planningCommands[0].repositorySha,'remote-sha')});


test('unchanged local helper save is a true no-op and preserves repository evidence',()=>{const item=helperItem('prompt','same','text');const local=state.normalizePlanningHelperLocalSnapshot({schemaVersion:1,savedAt:'2026-08-16T00:00:00Z',planningCommands:[],helperItems:[state.normalizeHelperRecord({item,repositoryKnown:true,repositorySha:'sha-1'})]});const prepared=runtime.prepareLocalHelperSave(local,{kind:'prompt',id:'same',title:item.title,text:item.text,createdAt:item.createdAt},'2026-08-17T00:00:00Z');assert.equal(prepared.changed,false);assert.equal(prepared.item.updatedAt,item.updatedAt);assert.equal(prepared.record.repositoryKnown,true);assert.equal(prepared.record.repositorySha,'sha-1');assert.equal(prepared.snapshot,local)});

test('real local helper edit updates timestamp and clears exact repository evidence',()=>{const item=helperItem('prompt','changed','old');const local=state.normalizePlanningHelperLocalSnapshot({schemaVersion:1,savedAt:'2026-08-16T00:00:00Z',planningCommands:[],helperItems:[state.normalizeHelperRecord({item,repositoryKnown:true,repositorySha:'sha-1'})]});const prepared=runtime.prepareLocalHelperSave(local,{kind:'prompt',id:'changed',title:item.title,text:'new',createdAt:item.createdAt},'2026-08-17T00:00:00Z');assert.equal(prepared.changed,true);assert.equal(prepared.item.updatedAt,'2026-08-17T00:00:00.000Z');assert.equal(prepared.record.repositoryKnown,false);assert.equal(prepared.record.repositorySha,'');assert.equal(prepared.record.item.text,'new')});

test('verified remote result remains success when only local evidence persistence fails',async()=>{const result=await runtime.persistVerifiedRepositoryResult(async()=>{throw new Error('quota')},{}, {ok:true,action:'update',path:'planning/helper-library/prompts/p.prompt.md',sha:'remote-sha'}, {owner:'o',repo:'r',branch:'main'}, ()=>({promptEntries:['old']}));assert.equal(result.ok,true);assert.equal(result.sha,'remote-sha');assert.equal(result.localSnapshotUpdated,false);assert.match(result.localSnapshotError,/quota/);assert.deepEqual(result.promptEntries,['old'])});

test('repository source change clears exact repository evidence without deleting local content',()=>{const local=snapshot();const cleared=runtime.clearRepositoryEvidence(local);assert.equal(cleared.planningCommands[0].definition.id,'a');assert.equal(cleared.planningCommands[0].repositoryKnown,false);assert.equal(cleared.planningCommands[0].repositorySha,'');assert.equal(cleared.helperItems.length,2);assert.equal(cleared.helperItems.every((record)=>!record.repositoryKnown&&!record.repositorySha),true)});


test('restore reconciles repository-backed records but preserves local-only content without inventing SHA',()=>{const remoteOld=def('remote-old','remote old'),remoteKeep=def('remote-keep','remote keep'),localOnly=helperItem('prompt','local-only','keep me');const local=state.normalizePlanningHelperLocalSnapshot({schemaVersion:1,savedAt:'2026-08-16T00:00:00Z',planningCommands:[state.normalizeCommandRecord({definition:remoteOld,repositoryKnown:true,repositorySha:'old-sha'})],helperItems:[state.normalizeHelperRecord({item:localOnly,repositoryKnown:false})]});const merged=runtime.mergeChatImport(local,{definitions:[remoteKeep],helperItems:[]},'restore');assert.equal(merged.removedRepositoryCommands,1);assert.equal(merged.snapshot.planningCommands.length,1);assert.equal(merged.snapshot.planningCommands[0].definition.id,'remote-keep');assert.equal(merged.snapshot.planningCommands[0].repositoryKnown,true);assert.equal(merged.snapshot.planningCommands[0].repositorySha,'');assert.equal(merged.snapshot.helperItems.length,1);assert.equal(merged.snapshot.helperItems[0].item.id,'local-only');assert.equal(merged.snapshot.helperItems[0].repositoryKnown,false)});


test('planning command local draft edit validates catalog, preserves tracked provenance and clears exact repository evidence',()=>{const original=def('tracked','tracked');const local=state.normalizePlanningHelperLocalSnapshot({schemaVersion:1,savedAt:'2026-08-16T00:00:00Z',planningCommands:[state.normalizeCommandRecord({definition:original,repositoryKnown:true,repositoryTracked:true,repositorySha:'sha'})],helperItems:[]});const changed={...original,description:'changed locally'};const prepared=runtime.prepareLocalCommandSave(local,changed,'tracked');assert.equal(prepared.changed,true);assert.equal(prepared.record.repositoryKnown,false);assert.equal(prepared.record.repositoryTracked,true);assert.equal(prepared.record.repositorySha,'');assert.equal(prepared.record.definition.description,'changed locally')});

test('new planning command draft is unregistered and existing command id/file cannot be renamed in-place',()=>{const local=state.normalizePlanningHelperLocalSnapshot({schemaVersion:1,savedAt:'2026-08-16T00:00:00Z',planningCommands:[state.normalizeCommandRecord({definition:def('a'),repositoryKnown:true,repositoryTracked:true})],helperItems:[]});const newDef=def('new-one','new one');const created=runtime.prepareLocalCommandSave(local,newDef);assert.equal(created.record.repositoryTracked,false);assert.equal(created.snapshot.planningCommands.length,2);assert.throws(()=>runtime.prepareLocalCommandSave(local,{...def('a'),id:'renamed',file:'renamed.command.md'},'a'),/cannot change its id or file/)})

test('local Delete removes even a registered command from Helper only and records a tombstone',()=>{const local=snapshot();const next=runtime.deleteLocalCommandFromSnapshot(local,'a');assert.equal(next.planningCommands.some((record)=>record.definition.id==='a'),false);assert.deepEqual(next.hiddenCommandIds,['a']);});

test('explicit GitHub sync can restore a locally deleted command and clears its tombstone',()=>{const local=runtime.deleteLocalCommandFromSnapshot(snapshot(),'a');const definition=def('a');const merged=runtime.mergeRemoteMissing(local,{commands:[{path:'planning/commands/a.command.md',sha:'fresh',definition,rawContent:codec.renderCommandDefinitionDocument(definition)}],helperItems:[]});assert.equal(merged.snapshot.planningCommands.some((record)=>record.definition.id==='a'),true);assert.deepEqual(merged.snapshot.hiddenCommandIds,[]);});

test('local Delete hides a Use Case without changing canonical semantic definitions',()=>{const local=snapshot();const id='UC-PLAN-DOMAIN';assert.ok(semantic.USE_CASE_DEFINITIONS.some((entry)=>entry.id===id));const next=runtime.deleteLocalUseCaseFromSnapshot(local,id);assert.ok(next.hiddenUseCaseIds.includes(id));const materialized=runtime.materializeSnapshot(next);assert.equal(materialized.useCaseEntries.some((entry)=>entry.id===id),false);assert.ok(semantic.USE_CASE_DEFINITIONS.some((entry)=>entry.id===id));});

