import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const codec=require('../src/helper-library-codec.js');
const {RepositoryHelperLibraryService}=require('../src/repository-helper-library-service.js');
function item(kind,id,title=id,text='text'){return codec.normalizeHelperLibraryItem({kind,id,title,text,createdAt:'2026-08-16T00:00:00Z',updatedAt:'2026-08-16T00:00:00Z'})}
function record(value,sha='sha'){const path=codec.helperLibraryTargetPath(value);return{type:'file',path,name:path.split('/').pop(),sha,content:codec.renderHelperLibraryDocument(value)}}
function fakeClient(records=[]){const map=new Map(records.map((row)=>[row.path,row]));const calls={list:[],read:[],save:[]};return{calls,client:{async listDirectory(path){calls.list.push(path);const rows=[...map.values()].filter((row)=>row.path.startsWith(`${path}/`));if(!rows.length){const e=new Error('missing');e.kind='not_found';throw e;}return rows.map(({type,path,name,sha})=>({type,path,name,sha}))},async read(path){calls.read.push(path);const row=map.get(path);if(!row){const e=new Error('missing');e.kind='not_found';throw e;}return{path,sha:row.sha,content:row.content}},async saveVerified(input){calls.save.push(input);const sha=`saved-${calls.save.length}`;map.set(input.path,{type:'file',path:input.path,name:input.path.split('/').pop(),sha,content:input.content});return{path:input.path,sha,content:input.content}}}}}

test('listRemoteAll reads only command/prompt directory metadata and tolerates an absent kind directory',async()=>{const prompt=item('prompt','p','Prompt'),{client,calls}=fakeClient([record(prompt,'sp')]);const rows=await new RepositoryHelperLibraryService(client).listRemoteAll();assert.equal(rows.length,1);assert.equal(rows[0].kind,'prompt');assert.deepEqual(calls.read,[]);assert.deepEqual(calls.list,['planning/helper-library/commands','planning/helper-library/prompts'])});

test('readRemote parses exact prompt content',async()=>{const prompt=item('prompt','p','Prompt','A\n\nB'),{client}=fakeClient([record(prompt,'sp')]);const row=await new RepositoryHelperLibraryService(client).readRemote('planning/helper-library/prompts/p.prompt.md');assert.equal(row.item.text,'A\n\nB');assert.equal(row.sha,'sp')});

test('save creates prompts and updates helper commands with current remote SHA',async()=>{const prompt=item('prompt','new','New prompt'),command=item('command','c','Command','old'),existing=record(command,'sc'),{client,calls}=fakeClient([existing]);const service=new RepositoryHelperLibraryService(client);const created=await service.save(prompt);assert.equal(created.action,'create');assert.equal(calls.save[0].baseSha,'');const changed={...command,text:'changed',updatedAt:'2026-08-16T01:00:00.000Z'};const updated=await service.save(changed);assert.equal(updated.action,'update');assert.equal(calls.save[1].baseSha,'sc')});

test('save no-ops when repository bytes already equal the local helper item',async()=>{const prompt=item('prompt','p','Prompt'),{client,calls}=fakeClient([record(prompt,'sp')]);const result=await new RepositoryHelperLibraryService(client).save(prompt);assert.equal(result.action,'noop');assert.equal(calls.save.length,0)});

test('explicit save repairs a malformed deterministic remote helper file using its exact current SHA',async()=>{const local=item('command','bad','Bad','fixed'),path=codec.helperLibraryTargetPath(local),malformed={type:'file',path,name:path.split('/').pop(),sha:'broken-sha',content:'# Helper Command — Bad\n\n[PLANNING_HELPER_LIBRARY_ITEM]\n{"schemaVersion":1,"kind":"command","id":"bad","title":"Bad","text":"literal\nnewline"}\n[/PLANNING_HELPER_LIBRARY_ITEM]\n'},{client,calls}=fakeClient([malformed]);const result=await new RepositoryHelperLibraryService(client).save(local);assert.equal(result.action,'update');assert.equal(result.replacedMalformedRemote,true);assert.equal(calls.save[0].baseSha,'broken-sha');assert.equal(calls.save[0].content,codec.renderHelperLibraryDocument(local))});

test('save propagates same-content conflict recovery evidence',async()=>{const command=item('command','c','Command','old'),existing=record(command,'sc'),{client}=fakeClient([existing]);client.saveVerified=async(input)=>({path:input.path,sha:'fresh',content:input.content,recoveredAfterConflict:true});const changed={...command,text:'changed',updatedAt:'2026-08-16T01:00:00.000Z'};const result=await new RepositoryHelperLibraryService(client).save(changed);assert.equal(result.recoveredAfterConflict,true);assert.equal(result.replacedMalformedRemote,false)});
