import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const moduleRoot=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const repoRoot=path.resolve(moduleRoot,'../../../../..');
const semantic=require('../src/semantic-projections.js');
const codec=require('../src/command-definition-codec.js');
const directions=semantic.normalizeDirectionDefinitions(JSON.parse(fs.readFileSync(path.join(moduleRoot,'seed/directions.json'),'utf8')).items);
const useCases=semantic.normalizeUseCaseDefinitions(JSON.parse(fs.readFileSync(path.join(moduleRoot,'seed/use-cases.json'),'utf8')).items);
const read=(rel)=>fs.readFileSync(path.join(repoRoot,rel),'utf8');
function walk(dir,result=[]){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isDirectory())walk(p,result);else if(entry.isFile()&&entry.name.toLowerCase()==='use-case-registry.md')result.push(p)}return result}
function canonicalUcIds(){const ids=[];for(const file of walk(path.join(repoRoot,'planning'))){const lines=fs.readFileSync(file,'utf8').split(/\r?\n/),status=String(lines.find((line)=>/^Status:/i.test(line))||'').toLowerCase();if(status.includes('legacy')||status.includes('historical')||status.includes('compatibility'))continue;for(const line of lines){let m=line.match(/^#{2,3} `((?:UC-[A-Z0-9-]+))` — /);if(!m)m=line.match(/^\| `((?:UC-[A-Z0-9-]+))` \|/);if(m&&!ids.includes(m[1]))ids.push(m[1])}}return ids}
function canonicalDirectionIds(){const ids=[];for(const line of read('planning/direction-registry.md').split(/\r?\n/)){const m=line.match(/^\| `((?:DIR-[A-Z0-9-]+))` \|/);if(m&&!ids.includes(m[1]))ids.push(m[1])}return ids}
function exactCaseExists(rel){let current=repoRoot;for(const segment of rel.split('/')){if(!fs.existsSync(current))return false;const names=fs.readdirSync(current);if(!names.includes(segment))return false;current=path.join(current,segment)}return fs.existsSync(current)}

test('generated Direction seed contains every current root Direction exactly once',()=>{const expected=canonicalDirectionIds(),actual=directions.map((d)=>d.id);assert.equal(new Set(actual).size,actual.length);assert.deepEqual([...actual].sort(),[...expected].sort());assert.equal(actual.length,11)});

test('generated Use-Case seed contains every current canonical UC exactly once',()=>{const expected=canonicalUcIds(),actual=useCases.map((u)=>u.id);assert.equal(new Set(actual).size,actual.length);assert.deepEqual([...actual].sort(),[...expected].sort());assert.equal(actual.length,expected.length);assert.ok(!actual.some((id)=>id.startsWith('UC-RPKG-')),'legacy Replacement Package App capability IDs must not be projected as current UCs')});

test('all generated semantic source paths exist with exact repository casing',()=>{for(const definition of [...directions,...useCases])for(const source of definition.sources||[])assert.ok(exactCaseExists(source),`${definition.id}: missing/exact-case-invalid source ${source}`)});

test('every current Use Case resolves through exactly one current Direction',()=>{const ids=new Set(directions.map((d)=>d.id));for(const uc of useCases)assert.ok(ids.has(uc.directionId),`${uc.id}: missing current Direction`)});

test('Use-Case semantic bodies remain thin owner-route projections with explicit permission boundary',()=>{const domain=useCases.find((u)=>u.id==='UC-PLAN-DOMAIN');assert.ok(domain);for(const mode of ['adaptive','full']){const body=semantic.buildSemanticBody('use_case',domain,mode);assert.match(body,/\[PLANNING_USE_CASE\]/);assert.match(body,/use_case_id:\n  UC-PLAN-DOMAIN/);assert.match(body,/route_resolution:/);assert.match(body,/current Main Owner \/ Owner Route/);assert.match(body,/Semantic planning\/read context only/)}assert.match(semantic.buildSemanticBody('use_case',domain,'full'),/Full use_case reading is required/)});

test('all visible repository commands resolve through at least one current Direction',()=>{const directionIds=new Set(directions.map((d)=>d.id)),commandDir=path.join(repoRoot,'planning','commands');for(const name of fs.readdirSync(commandDir).filter((n)=>n.endsWith('.command.md'))){const definition=codec.parseCommandDefinitionDocument(fs.readFileSync(path.join(commandDir,name),'utf8'));if(definition.palette!==true)continue;const ids=semantic.directionIdsForCommand(definition,useCases);assert.ok(ids.length,`${definition.id}: no Direction`);for(const id of ids)assert.ok(directionIds.has(id),`${definition.id}: unknown Direction ${id}`)}});

test('important direct command-backed UCs resolve to their bespoke command routes',()=>{for(const [id,commandId] of [['UC-REPO-AUDIT-REVIEW','review_audit.recheck'],['UC-PLAN-ARCH-WORKSPACE-USES','workspace_uses.discover'],['UC-PLAN-ARCH-DISCOVER-WEUC','architecture_weuc.discover'],['UC-PLAN-DOMAIN','application_domain.plan'],['UC-PLAN-SLICE','application_slice.plan'],['UC-PLAN-TEST-PLAN','practical_testing.plan'],['UC-DOC-ORIENT','documentation_principles.read'],['UC-PLAN-ORIENT','application_sds.bootstrap']]){const uc=useCases.find((u)=>u.id===id);assert.ok(uc,id);assert.equal(uc.commandId,commandId,id)}});

test('Application Realization projection is generic while its owner carries runtime/architecture handoff semantics',()=>{const realization=useCases.find((u)=>u.id==='UC-PLAN-REALIZATION');assert.ok(realization);assert.equal(realization.label,'Review / Compare High-Level Application Realization');assert.match(realization.instruction,/current canonical registry/);assert.doesNotMatch(realization.instruction,/hardcoded|pre-Domain comparative evidence/);const owner=read('planning/documentation/application-planning/application-realization-workflow.md');assert.match(owner,/Architecture Cost Handoff/);assert.match(owner,/runtime/i)});

test('Application SDS bootstrap stays distinct from Full SDS and owns proportional governance preflight',()=>{const uc=useCases.find((u)=>u.id==='UC-PLAN-ORIENT');assert.ok(uc);assert.equal(uc.commandId,'application_sds.bootstrap');const bootstrap=codec.parseCommandDefinitionDocument(read('planning/commands/bootstrap-application-sds-planning.command.md'));const full=codec.parseCommandDefinitionDocument(read('planning/commands/work-full-sds.command.md'));assert.notEqual(bootstrap.id,full.id);assert.equal(bootstrap.permissionMode,'read-only');assert.match(bootstrap.meaning,/governance bootstrap/i);assert.match(bootstrap.meaning,/not selection of the Full SDS profile/i);assert.match(bootstrap.traversalReadMode,/Reuse current reliable SDS governance/i);assert.match(bootstrap.traversalReadMode,/targeted refresh/i);const owner=read('planning/documentation/application-planning/application-planning-governance-read-workflow.md');assert.match(owner,/Do \*\*not\*\* invalidate a current SDS bootstrap merely because a new snapshot, commit, branch or repository target appears/);assert.match(owner,/Do not require a separate `бутстреп сдс` invocation/)});

test('legacy Full SDS commands retain their explicit preflight owner while narrow current commands do not inherit it automatically',()=>{const owner='planning/documentation/application-planning/application-planning-governance-read-workflow.md';for(const [file,id] of [['work-mini-sds.command.md','application_sds.mini'],['work-modular-sds.command.md','application_sds.modular'],['work-full-sds.command.md','application_sds.full']]){const command=codec.parseCommandDefinitionDocument(read(`planning/commands/${file}`));assert.equal(command.id,id);assert.ok(command.ownerFiles.includes(owner),`${id}: missing complete SDS governance preflight owner`);assert.match(command.traversalReadMode,/Reuse current reliable SDS governance/i);assert.match(command.traversalReadMode,/full SDS governance preflight/i)}const narrow=codec.parseCommandDefinitionDocument(read('planning/commands/plan-solution.command.md'));assert.equal(narrow.id,'application_solution.plan');assert.ok(!narrow.ownerFiles.includes(owner),'narrow application_solution.plan must not imply complete SDS governance solely because it produces a result');const registry=read('planning/documentation/application-planning/use-case-registry.md');assert.match(registry,/commands whose current command\/semantic owner route explicitly requires complete SDS governance/);assert.match(registry,/do \*\*not\*\* trigger a full SDS bootstrap merely because they return a planning result/)});

test('retired collect-ideas aliases are hidden thin routes into current IDTSPE/SDS owners, not the old Idea runtime',()=>{const files=['collect-ideas.command.md','collect-application-ideas.command.md','collect-modular-application-ideas.command.md','collect-scenario-ideas.command.md','collect-domain-ideas.command.md','collect-slice-ideas.command.md'];for(const file of files){const command=codec.parseCommandDefinitionDocument(read(`planning/commands/${file}`));assert.equal(command.palette,false,command.id);assert.match(command.description,/legacy compatibility/i,command.id);assert.match(command.meaning,/IDTSPE|Target Module/i,command.id);assert.match(command.keyReminders.join(' '),/Do not execute or revive the former collect-ideas shell/i,command.id);for(const owner of command.ownerFiles){assert.doesNotMatch(owner,/idea-planning-principles|idea-review-and-planning-workflow|IDEA-REVIEW-TEMPLATE|profiles\/sds-planning-profiles|application-planning\/use-case-registry|architecture-planning\/use-case-registry|testing-planning\/use-case-registry/,`${command.id}: legacy owner ${owner}`)}}const generic=read('planning/commands/collect-ideas.command.md');assert.match(generic,/Scope: legacy compatibility command alias/);assert.doesNotMatch(generic,/Reusable Idea, SDS\/UCDS and reviewability behavior remains/);});



test('IDTSPE and SDS bootstrap commands load governance without forming or executing Targets',()=>{
  for(const file of ['bootstrap-idtspe.command.md','bootstrap-application-sds-planning.command.md']){
    const command=codec.parseCommandDefinitionDocument(read(`planning/commands/${file}`));
    assert.equal(command.methodologyBinding?.surfaceKind,'BOOTSTRAP',command.id);
    assert.equal(command.methodologyBinding?.hostTargetPolicy,'NONE',command.id);
    assert.match(command.activeContextBehavior,/governance/i,command.id);
    assert.match(command.activeContextBehavior,/Do not perform Target Formation/i,command.id);
    assert.match(command.activeContextBehavior,/Do not .*infer CREATE\/REFINE\/EXTEND\/REVALIDATE\/REPAIR/i,command.id);
    assert.match(command.keyReminders.join(' '),/Bootstrap is governance orientation only/i,command.id);
  }
});

test('root Architecture and Testing Directions route to installed IDTSPE/SDS authority rather than legacy planning families',()=>{const registry=read('planning/direction-registry.md');const architecture=registry.split(/\r?\n/).find((line)=>line.startsWith('| `DIR-PLAN-ARCHITECTURE`'));const testing=registry.split(/\r?\n/).find((line)=>line.startsWith('| `DIR-PLAN-TESTING`'));assert.ok(architecture);assert.ok(testing);for(const row of [architecture,testing]){assert.match(row,/documentation\/idtspe-methodology\/active\/profiles\/sds/);assert.doesNotMatch(row,/documentation\/(architecture-planning|testing-planning)\/(direction-registry|use-case-registry)\.md/)}assert.match(architecture,/TM-WEUC/);assert.match(architecture,/WEUC Lens/);assert.match(testing,/target-modules\/README\.md/)});

test('Test Strategy can persist a registry-like realization map without duplicating test code',()=>{const owner=read('planning/documentation/idtspe-methodology/active/profiles/sds/target-modules/TM-TEST-STRATEGY.md');assert.match(owner,/Test Realization \/ Topology Registry/);assert.match(owner,/test suite\/class.*setup\/fixture\/harness\/helper/s);assert.match(owner,/do not duplicate test bodies, assertions, method inventories or obvious class structure/i);assert.match(owner,/TEST-REALIZATION-MAP\.md/);const command=codec.parseCommandDefinitionDocument(read('planning/commands/plan-testing-strategy.command.md'));assert.match(command.expectedOutput,/Test Realization \/ Topology Registry/);assert.match(command.helperPresentation.whatYouGet,/test suite\/class.*setup\/fixture\/harness\/helper/)});

test('SDS profiles keep same quality and explicit Step 0–4 with pre-implementation test planning',()=>{const text=read('planning/documentation/profiles/sds-planning-profiles.md');assert.match(text,/same planning-quality contract/i);assert.match(text,/STEP 0 — WHY \/ SOLUTION DISCOVERY/);assert.match(text,/Scenario DATA/);assert.match(text,/Behavior Items/);assert.match(text,/application-plan\.md/);assert.match(text,/domain-draft\.md/);assert.match(text,/slices\.md/);assert.match(text,/contextual WEUC Instances/);assert.match(text,/Test Design/);assert.match(text,/Practical Test Plan/);assert.match(text,/STEP 4 — PRACTICAL REALIZATION FEEDBACK/);assert.match(text,/actual evidence/i);assert.doesNotMatch(text,/Goal Map/i)});

test('semantic runtime source contains no maintained current Direction/UC catalog identities',()=>{const source=fs.readFileSync(path.join(moduleRoot,'src/semantic-projections.js'),'utf8');for(const identity of ['UC-PLAN-DOMAIN','UC-REPO-CURRENT-STATE','DIR-PLAN-SOLUTION','application_domain.plan'])assert.doesNotMatch(source,new RegExp(identity.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(source,/normalizeDirectionDefinitions/);assert.match(source,/normalizeUseCaseDefinitions/)});
