package obs.rpkg;

import java.net.URI;
import java.net.http.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.zip.*;

public final class ChatBridgeTests {
    static int passed,failed;static Path tmp;
    public static void main(String[] args)throws Exception{tmp=Files.createTempDirectory("obs-chat-bridge-tests-");try{run();}finally{deleteTree(tmp);}System.out.println("CHAT-BRIDGE RESULT passed="+passed+" failed="+failed);if(failed>0)System.exit(1);}
    static void run()throws Exception{
        test("pairing token persists",()->{StateStore st=new StateStore(tmp.resolve("token-state"));String a=new ChatBridgeService(st).pairingToken(),b=new ChatBridgeService(st).pairingToken();eq(a,b,"pairing token changed");ok(a.matches("[0-9a-f]{64}"),"pairing token format");});
        test("extension needs no clipboard permission and hides hash terminology from delivery error",()->{
            Path extension=Path.of("chatgpt-bridge-extension");String manifest=Files.readString(extension.resolve("manifest.json"),StandardCharsets.UTF_8),content=Files.readString(extension.resolve("src/content.js"),StandardCharsets.UTF_8);
            ok(!manifest.contains("\"clipboardWrite\""),"unnecessary clipboardWrite permission remains");ok(!manifest.contains("\"clipboardRead\""),"unnecessary clipboardRead permission remains");
            ok(content.contains("Artifact changed during delivery."),"neutral artifact-change error missing");ok(!content.contains("Artifact SHA-256 changed during delivery."),"user-facing artifact error exposes SHA terminology");
        });
        test("browser send path reacquires a connected Send control after SendClicked staging",()->{
            String adapter=Files.readString(Path.of("chatgpt-bridge-extension/src/chatgpt-adapter.js"),StandardCharsets.UTF_8);
            int staged=adapter.indexOf("await stageSend();"),fresh=adapter.indexOf("const button = readySendButton(root);",staged),click=adapter.indexOf("button.click();",fresh);
            ok(staged>=0&&fresh>staged&&click>fresh,"Send control is not reacquired after SendClicked staging");
            ok(adapter.substring(fresh,click).indexOf("await ")<0,"async gap remains between fresh Send lookup and click");
            ok(adapter.contains("b.isConnected"),"fresh Send control is not required to be connected");
            ok(adapter.contains("const liveEditor = composer();"),"post-send confirmation still depends on stale composer reference");
        });
        test("ChangeSet binding persists and remembers conversation",()->{StateStore st=new StateStore(tmp.resolve("binding-state"));ChatBridgeService s=new ChatBridgeService(st);s.replaceInventory(List.of(chat("conv12345678","Planning","https://chatgpt.com/c/conv12345678",11,12)));Core.ChatBinding b=s.bind("cs-one","conv12345678");eq(b.title(),"Planning","binding title");eq(new ChatBridgeService(st).binding("cs-one").conversationKey(),"conv12345678","binding did not persist");});
        test("automatic ReviewDiff task deduplicates one review attempt",()->{StateStore st=new StateStore(tmp.resolve("dedupe-state"));ChatBridgeService s=serviceWithChat(st,"conv22345678",21);Core.ChatBinding b=s.bind("cs","conv22345678");Core.ReviewDiff r=review(tmp.resolve("dedupe.diff"),"review-one","diff");Core.ChatTaskInfo a=s.enqueueReview(changeSet("cs","work"),r,b,false),c=s.enqueueReview(changeSet("cs","work"),r,b,false);eq(a.taskId(),c.taskId(),"automatic review task duplicated");});
        test("new auto ReviewDiff supersedes older Pending task",()->{StateStore st=new StateStore(tmp.resolve("supersede-state"));ChatBridgeService s=serviceWithChat(st,"conv32345678",31);Core.ChatBinding b=s.bind("cs","conv32345678");Core.ChatTaskInfo old=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("old.diff"),"old","old"),b,false);Core.ChatTaskInfo fresh=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("fresh.diff"),"fresh","fresh"),b,false);eq(s.taskInfo(old.taskId()).status(),"Cancelled","old auto task not cancelled");eq(s.claim("conv32345678",31).get("taskId"),fresh.taskId(),"fresh task not claimable");});
        test("manual current ReviewDiff may create an explicit second delivery",()->{StateStore st=new StateStore(tmp.resolve("manual-state"));ChatBridgeService s=serviceWithChat(st,"conv42345678",41);Core.ChatBinding b=s.bind("cs","conv42345678");Core.ReviewDiff r=review(tmp.resolve("manual.diff"),"review-one","diff");Core.ChatTaskInfo a=s.enqueueReview(changeSet("cs","work"),r,b,false),c=s.enqueueReview(changeSet("cs","work"),r,b,true);ok(!a.taskId().equals(c.taskId()),"manual send was deduplicated unexpectedly");});
        test("empty ReviewDiff becomes NoChanges and is never claimable",()->{StateStore st=new StateStore(tmp.resolve("empty-state"));ChatBridgeService s=serviceWithChat(st,"conv52345678",51);Core.ChatBinding b=s.bind("cs","conv52345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("empty.diff"),"empty",""),b,false);eq(t.status(),"NoChanges","empty review task state");ok(s.claim("conv52345678",51).isEmpty(),"empty review was claimable");});
        test("claim requires tab to belong to exact conversation",()->{StateStore st=new StateStore(tmp.resolve("claim-chat-state"));ChatBridgeService s=serviceWithChat(st,"conv62345678",61);Core.ChatBinding b=s.bind("cs","conv62345678");s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("claim-chat.diff"),"r","x"),b,false);expect(Core.CHAT_BRIDGE_FAILED,()->s.claim("conv62345678",999));});
        test("only one tab claims and terminal Sent cannot change",()->{StateStore st=new StateStore(tmp.resolve("claim-state"));ChatBridgeService s=serviceWithChat(st,"conv72345678",71,72);Core.ChatBinding b=s.bind("cs","conv72345678");Core.ChatTaskInfo info=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("claim.diff"),"review-one","diff"),b,false);Map<String,Object> first=s.claim("conv72345678",71),second=s.claim("conv72345678",72);eq(first.get("taskId"),info.taskId(),"wrong task claimed");ok(second.isEmpty(),"second tab claimed same task");s.stagePreparing(info.taskId(),71,"conv72345678");s.stageSendClicked(info.taskId(),71,"conv72345678");s.result(info.taskId(),71,"conv72345678","Sent","ok");expect(Core.CHAT_BRIDGE_FAILED,()->s.result(info.taskId(),71,"conv72345678","UnknownAfterSend","rewrite"));eq(s.taskInfo(info.taskId()).status(),"Sent","terminal task changed");});
        test("SendClicked cannot transition back to FailedBeforeSend",()->{StateStore st=new StateStore(tmp.resolve("send-state"));ChatBridgeService s=serviceWithChat(st,"conv82345678",81);Core.ChatBinding b=s.bind("cs","conv82345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("send.diff"),"r","x"),b,false);s.claim("conv82345678",81);s.stagePreparing(t.taskId(),81,"conv82345678");s.stageSendClicked(t.taskId(),81,"conv82345678");expect(Core.CHAT_BRIDGE_FAILED,()->s.result(t.taskId(),81,"conv82345678","FailedBeforeSend","bad"));s.result(t.taskId(),81,"conv82345678","UnknownAfterSend","uncertain");});
        test("release before Send is retryable; release after SendClicked is unknown",()->{StateStore st=new StateStore(tmp.resolve("release-state"));ChatBridgeService s=serviceWithChat(st,"conv92345678",91,92);Core.ChatBinding b=s.bind("cs","conv92345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("release.diff"),"r","x"),b,false);s.claim("conv92345678",91);eq(s.release(t.taskId(),91,"conv92345678","closed"),"Pending","pre-send release");eq(s.claim("conv92345678",92).get("taskId"),t.taskId(),"released task not reclaimed");s.stagePreparing(t.taskId(),92,"conv92345678");s.stageSendClicked(t.taskId(),92,"conv92345678");eq(s.release(t.taskId(),92,"conv92345678","closed"),"UnknownAfterSend","post-send release");});
        test("tab navigation releases claimed task from old conversation",()->{StateStore st=new StateStore(tmp.resolve("navigation-state"));ChatBridgeService s=serviceWithChat(st,"convA2345678",101);Core.ChatBinding b=s.bind("cs","convA2345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("nav.diff"),"r","x"),b,false);s.claim("convA2345678",101);s.replaceInventory(List.of(chat("convB2345678","Other","https://chatgpt.com/c/convB2345678",101)));eq(s.taskInfo(t.taskId()).status(),"Pending","navigation did not release pre-send claim");});
        test("confirmed composer preparation failure becomes PreparedUnsent and is immutable",()->{StateStore st=new StateStore(tmp.resolve("prepared-unsent-state"));ChatBridgeService s=serviceWithChat(st,"convP2345678",105);Core.ChatBinding b=s.bind("cs","convP2345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("prepared.diff"),"prepared-review","x"),b,false);s.claim("convP2345678",105);s.stagePreparing(t.taskId(),105,"convP2345678");s.result(t.taskId(),105,"convP2345678","PreparedUnsent","content prepared but pre-send guard failed");eq(s.taskInfo(t.taskId()).status(),"PreparedUnsent","prepared failure state");expect(Core.CHAT_BRIDGE_FAILED,()->s.result(t.taskId(),105,"convP2345678","FailedBeforeSend","rewrite"));});
        test("Preparing blocks rebind and survives newer auto review",()->{StateStore st=new StateStore(tmp.resolve("preparing-rebind-state"));ChatBridgeService s=new ChatBridgeService(st);s.replaceInventory(List.of(chat("convQ2345678","A","https://chatgpt.com/c/convQ2345678",106),chat("convR2345678","B","https://chatgpt.com/c/convR2345678",107)));Core.ChatBinding b=s.bind("cs","convQ2345678");Core.ChatTaskInfo old=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("preparing-old.diff"),"old-review","old"),b,false);s.claim("convQ2345678",106);s.stagePreparing(old.taskId(),106,"convQ2345678");Core.ChatTaskInfo fresh=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("preparing-fresh.diff"),"fresh-review","fresh"),b,false);eq(s.taskInfo(old.taskId()).status(),"Preparing","new review cancelled composer-active task");eq(fresh.status(),"Pending","new review not queued behind composer-active task");expect(Core.CHAT_BRIDGE_FAILED,()->s.bind("cs","convR2345678"));expect(Core.CHAT_BRIDGE_FAILED,()->s.unbind("cs"));});
        test("Preparing tab cannot claim queued newer task",()->{StateStore st=new StateStore(tmp.resolve("preparing-claim-state"));ChatBridgeService s=serviceWithChat(st,"convV2345678",1111);Core.ChatBinding b=s.bind("cs","convV2345678");Core.ChatTaskInfo old=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("claim-old.diff"),"claim-old","old"),b,false);s.claim("convV2345678",1111);s.stagePreparing(old.taskId(),1111,"convV2345678");Core.ChatTaskInfo fresh=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("claim-new.diff"),"claim-new","new"),b,false);ok(s.claim("convV2345678",1111).isEmpty(),"tab claimed another task while composer preparation was active");eq(s.taskInfo(fresh.taskId()).status(),"Pending","new task changed while older task was preparing");});
        test("conversation serializes queued tasks across duplicate tabs",()->{StateStore st=new StateStore(tmp.resolve("conversation-serial-state"));ChatBridgeService s=serviceWithChat(st,"convW2345678",1121,1122);Core.ChatBinding b=s.bind("cs","convW2345678");Core.ChatTaskInfo old=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("serial-old.diff"),"serial-old","old"),b,true);Core.ChatTaskInfo fresh=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("serial-new.diff"),"serial-new","new"),b,true);eq(s.claim("convW2345678",1121).get("taskId"),old.taskId(),"oldest task was not claimed first");ok(s.claim("convW2345678",1122).isEmpty(),"duplicate tab claimed second task concurrently");s.result(old.taskId(),1121,"convW2345678","FailedBeforeSend","done");eq(s.claim("convW2345678",1122).get("taskId"),fresh.taskId(),"second task did not become claimable after first terminal result");});
        test("expired SendClicked is normalized before rebind",()->{StateStore st=new StateStore(tmp.resolve("expired-rebind-state"));ChatBridgeService s=new ChatBridgeService(st);s.replaceInventory(List.of(chat("convS2345678","A","https://chatgpt.com/c/convS2345678",108),chat("convT2345678","B","https://chatgpt.com/c/convT2345678",109)));Core.ChatBinding b=s.bind("cs","convS2345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("expired.diff"),"expired-review","x"),b,false);s.claim("convS2345678",108);s.stagePreparing(t.taskId(),108,"convS2345678");s.stageSendClicked(t.taskId(),108,"convS2345678");Path task=st.root.resolve("chat-handoffs").resolve(t.taskId()+".json");Map<String,Object> m=st.readObject(task);m.put("leaseUntil","2000-01-01T00:00:00Z");st.writeJson(task,m);Core.ChatBinding rebound=s.bind("cs","convT2345678");eq(rebound.conversationKey(),"convT2345678","expired SendClicked still blocked rebind");eq(s.taskInfo(t.taskId()).status(),"UnknownAfterSend","expired SendClicked not normalized");});
        test("bridge terminal event carries exact review identity",()->{StateStore st=new StateStore(tmp.resolve("event-state"));ChatBridgeService s=serviceWithChat(st,"convU2345678",110);List<ChatBridgeService.ChatEvent> events=new ArrayList<>();s.setEventSink(events::add);Core.ChatBinding b=s.bind("cs","convU2345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("event.diff"),"event-review","x"),b,false);s.claim("convU2345678",110);s.result(t.taskId(),110,"convU2345678","FailedBeforeSend","before paste");eq(events.size(),1,"terminal event count");eq(events.get(0).reviewAttemptId(),"event-review","event review identity");eq(events.get(0).changeSetId(),"cs","event ChangeSet identity");});
        test("archive Output routes only matching ReviewDiff events",()->{Set<String> current=new LinkedHashSet<>(List.of("review-B"));ChatBridgeService.ChatEvent oldEvent=new ChatBridgeService.ChatEvent(UUID.randomUUID().toString(),"reviewDiff","cs","review-A","FailedBeforeSend","old");ChatBridgeService.ChatEvent currentEvent=new ChatBridgeService.ChatEvent(UUID.randomUUID().toString(),"reviewDiff","cs","review-B","FailedBeforeSend","current");ok(!MainWindow.eventBelongsToOutput(current,oldEvent),"late old-archive event bled into current Output");ok(MainWindow.eventBelongsToOutput(current,currentEvent),"current review event was not routed to Output");});
        test("heartbeat preserves exact claimed task",()->{StateStore st=new StateStore(tmp.resolve("heartbeat-state"));ChatBridgeService s=serviceWithChat(st,"convC2345678",111);Core.ChatBinding b=s.bind("cs","convC2345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("hb.diff"),"r","x"),b,false);s.claim("convC2345678",111);eq(s.heartbeat(t.taskId(),111,"convC2345678"),"Claimed","heartbeat state");eq(s.claim("convC2345678",111).get("taskId"),t.taskId(),"same-tab reclaim changed task");});
        test("rebind cancels unsent tasks and SendClicked blocks rebind",()->{StateStore st=new StateStore(tmp.resolve("rebind-state"));ChatBridgeService s=new ChatBridgeService(st);s.replaceInventory(List.of(chat("convD2345678","A","https://chatgpt.com/c/convD2345678",121),chat("convE2345678","B","https://chatgpt.com/c/convE2345678",122)));Core.ChatBinding a=s.bind("cs","convD2345678");Core.ChatTaskInfo pending=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("rebind1.diff"),"r1","x"),a,false);s.bind("cs","convE2345678");eq(s.taskInfo(pending.taskId()).status(),"Cancelled","rebind did not cancel pending old-chat task");Core.ChatBinding b=s.binding("cs");Core.ChatTaskInfo sending=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("rebind2.diff"),"r2","y"),b,false);s.claim("convE2345678",122);s.stagePreparing(sending.taskId(),122,"convE2345678");s.stageSendClicked(sending.taskId(),122,"convE2345678");expect(Core.CHAT_BRIDGE_FAILED,()->s.bind("cs","convD2345678"));expect(Core.CHAT_BRIDGE_FAILED,()->s.unbind("cs"));});
        test("queued ReviewDiff bytes are immutable by fingerprint",()->{StateStore st=new StateStore(tmp.resolve("review-bytes-state"));ChatBridgeService s=serviceWithChat(st,"convF2345678",131);Core.ChatBinding b=s.bind("cs","convF2345678");Path p=tmp.resolve("bytes.diff");Core.ReviewDiff r=review(p,"r","one");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),r,b,false);Map<String,Object> claim=s.claim("convF2345678",131);Files.writeString(p,"two",StandardCharsets.UTF_8);expect(Core.CHAT_BRIDGE_FAILED,()->s.verifiedPayloadSource(t.taskId(),ticket(claim)));});
        test("snapshot bytes are fingerprinted and snapshot is attach-only",()->{StateStore st=new StateStore(tmp.resolve("snapshot-state"));ChatBridgeService s=serviceWithChat(st,"convG2345678",141);Path zip=snapshotZip(tmp.resolve("snapshot.zip"));Core.ChatTaskInfo info=s.enqueueSnapshot(zip,"convG2345678");ok(!info.autoSend(),"snapshot requested auto send");Map<String,Object> claim=s.claim("convG2345678",141);ChatBridgeService.PayloadSource source=s.verifiedPayloadSource(info.taskId(),ticket(claim));eq(source.sha256(),claim.get("artifactSha256"),"snapshot hash not carried to claim");s.stagePreparing(info.taskId(),141,"convG2345678");s.result(info.taskId(),141,"convG2345678","Attached","ready");eq(s.taskInfo(info.taskId()).status(),"Attached","snapshot result not persisted");});
        test("mutated snapshot payload is rejected",()->{StateStore st=new StateStore(tmp.resolve("snapshot-mutate-state"));ChatBridgeService s=serviceWithChat(st,"convH2345678",151);Path zip=snapshotZip(tmp.resolve("snapshot-mutate.zip"));Core.ChatTaskInfo info=s.enqueueSnapshot(zip,"convH2345678");Map<String,Object> claim=s.claim("convH2345678",151);Files.write(zip,new byte[]{1,2,3});expect(Core.CHAT_BRIDGE_FAILED,()->s.verifiedPayloadSource(info.taskId(),ticket(claim)));});
        test("generic ZIP cannot be attached as V1 snapshot",()->{StateStore st=new StateStore(tmp.resolve("generic-state"));ChatBridgeService s=serviceWithChat(st,"convI2345678",161);Path zip=tmp.resolve("generic.zip");try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(zip))){put(z,"x.txt","x");}expect(Core.CHAT_BRIDGE_FAILED,()->s.enqueueSnapshot(zip,"convI2345678"));});
        test("legacy unfingerprinted tasks are cancelled without delivery",()->{StateStore st=new StateStore(tmp.resolve("legacy-state"));String id=UUID.randomUUID().toString();Map<String,Object> old=new LinkedHashMap<>();old.put("schemaVersion",1);old.put("taskId",id);old.put("kind","reviewDiff");old.put("conversationKey","convL2345678");old.put("status","Pending");old.put("artifactPath",tmp.resolve("legacy.diff").toString());old.put("createdAt",java.time.Instant.now().toString());old.put("updatedAt",java.time.Instant.now().toString());st.writeJson(st.root.resolve("chat-handoffs").resolve(id+".json"),old);ChatBridgeService s=serviceWithChat(st,"convL2345678",181);eq(s.taskInfo(id).status(),"Cancelled","legacy task remained deliverable");ok(s.claim("convL2345678",181).isEmpty(),"legacy task was claimed");});
        test("semantic External Interaction cancel retains prepared content state and blocks post-send rewrite",()->{StateStore st=new StateStore(tmp.resolve("interaction-cancel-state"));ChatBridgeService s=serviceWithChat(st,"convK2345678",1711);Core.ChatBinding b=s.bind("cs","convK2345678");Core.ChatTaskInfo t=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("interaction-cancel.diff"),"interaction-review","x"),b,true);ok(s.externalInteractions().stream().anyMatch(x->x.interactionId().equals(t.taskId())&&x.cancellable()),"queued semantic interaction missing");s.claim("convK2345678",1711);s.stagePreparing(t.taskId(),1711,"convK2345678");Core.ExternalInteraction cancelled=s.cancelExternalInteraction(t.taskId());eq(cancelled.state(),"Cancelled","prepared interaction not cancelled");ok(cancelled.message().contains("prepared content retained"),"prepared cancel did not retain-content truth");eq(s.taskInfo(t.taskId()).status(),"Cancelled","technical task did not stop after prepared cancel");Core.ChatTaskInfo sending=s.enqueueReview(changeSet("cs","work"),review(tmp.resolve("interaction-send.diff"),"send-review","y"),b,true);s.claim("convK2345678",1711);s.stagePreparing(sending.taskId(),1711,"convK2345678");s.stageSendClicked(sending.taskId(),1711,"convK2345678");Core.ExternalInteraction visible=s.externalInteractions().stream().filter(x->x.interactionId().equals(sending.taskId())).findFirst().orElseThrow();ok(!visible.cancellable(),"SendClicked interaction advertised unsafe Cancel");expect(Core.CHAT_BRIDGE_FAILED,()->s.cancelExternalInteraction(sending.taskId()));eq(s.taskInfo(sending.taskId()).status(),"SendClicked","cancel rewrote possible-send truth");});
        test("External Interaction list is current/actionable and terminal retry gets new identity",()->{Path stateRoot=tmp.resolve("interaction-history-state");StateStore st=new StateStore(stateRoot);ChatBridgeService service=serviceWithChat(st,"convM2345678",1811);Core.ChatBinding b=service.bind("cs","convM2345678");Core.ChatTaskInfo sent=service.enqueueReview(changeSet("cs","work"),review(tmp.resolve("terminal.diff"),"terminal","x"),b,true);service.claim("convM2345678",1811);service.stagePreparing(sent.taskId(),1811,"convM2345678");service.stageSendClicked(sent.taskId(),1811,"convM2345678");service.result(sent.taskId(),1811,"convM2345678","Sent","done");ok(service.externalInteractions().stream().noneMatch(x->x.interactionId().equals(sent.taskId())),"ordinary terminal success accumulated in semantic list");Core.ChatTaskInfo cancelled=service.enqueueReview(changeSet("cs","work"),review(tmp.resolve("cancelled.diff"),"cancelled","y"),b,true);service.cancelExternalInteraction(cancelled.taskId());ok(service.externalInteractions().stream().noneMatch(x->x.interactionId().equals(cancelled.taskId())),"Cancelled interaction accumulated in semantic list");Core.ChatTaskInfo retry=service.enqueueReview(changeSet("cs","work"),review(tmp.resolve("retry.diff"),"retry","z"),b,true);ok(!retry.taskId().equals(cancelled.taskId()),"retry reused cancelled interaction identity");Core.ExternalInteraction active=service.externalInteractions().stream().filter(x->x.interactionId().equals(retry.taskId())).findFirst().orElseThrow();ok(active.destination().contains("convM2345678"),"interaction destination hid exact conversation key");ok(active.source().endsWith(".diff"),"interaction source was not exposed");service.claim("convM2345678",1811);service.stagePreparing(retry.taskId(),1811,"convM2345678");service.stageSendClicked(retry.taskId(),1811,"convM2345678");service.result(retry.taskId(),1811,"convM2345678","UnknownAfterSend","uncertain");ok(service.externalInteractions().stream().anyMatch(x->x.interactionId().equals(retry.taskId())&&"UnknownAfterSend".equals(x.state())),"attention-requiring uncertainty disappeared from semantic list");ChatBridgeService restarted=serviceWithChat(new StateStore(stateRoot),"convM2345678",1811);ok(restarted.externalInteractions().stream().anyMatch(x->x.interactionId().equals(retry.taskId())),"persisted UnknownAfterSend uncertainty disappeared after restart");});
        test("task ids cannot traverse state root",()->{StateStore st=new StateStore(tmp.resolve("traversal-state"));ChatBridgeService s=new ChatBridgeService(st);expect(Core.CHAT_BRIDGE_FAILED,()->s.taskInfo("../../outside"));});
        test("Core Refresh Review auto-queues only after ChangeSet is bound",()->{Path repo=tmp.resolve("core-refresh-repo");Files.createDirectories(repo);git(repo,"init","-b","main");git(repo,"config","user.name","OBS Test");git(repo,"config","user.email","obs@example.invalid");Files.writeString(repo.resolve("a.txt"),"base",StandardCharsets.UTF_8);git(repo,"add",".");git(repo,"commit","-m","base");git(repo,"remote","add","origin","https://github.com/example/core-refresh.git");StateStore st=new StateStore(tmp.resolve("core-refresh-state"));Core core=new Core(st);Core.RepositoryConfig target=core.registerRepository("Core Refresh",repo);Core.ChangeSet cs=changeSet(UUID.randomUUID().toString(),"Core refresh");cs.repositoryRoot=repo.toAbsolutePath().normalize().toString();cs.repositoryIdentity="github:example/core-refresh";cs.repositoryTargetId=target.id();cs.status="Active";cs.ownedPaths.add("a.txt");cs.createdAt=cs.updatedAt=java.time.Instant.now().toString();st.saveChangeSet(cs);core.chatBridgeService().replaceInventory(List.of(chat("convJ2345678","Review Chat","https://chatgpt.com/c/convJ2345678",171)));core.bindReviewChat(cs.changeSetId,"convJ2345678");ok(core.chatBridgeService().claim("convJ2345678",171).isEmpty(),"binding sent current review implicitly");Files.writeString(repo.resolve("a.txt"),"changed",StandardCharsets.UTF_8);Core.ReviewDiff review=core.refreshReview(cs.changeSetId);eq(core.chatBridgeService().claim("convJ2345678",171).get("reviewAttemptId"),review.attemptId(),"Refresh Review did not queue current review");});
        test("loopback server requires pairing token and rejects bad task id",()->{StateStore st=new StateStore(tmp.resolve("server-state"));ChatBridgeService service=new ChatBridgeService(st);String token=service.pairingToken();try(ChatBridgeServer server=ChatBridgeServer.start(service)){HttpClient client=HttpClient.newHttpClient();URI health=URI.create("http://127.0.0.1:"+ChatBridgeService.PORT+"/v1/health");HttpRequest good=HttpRequest.newBuilder(health).header("X-OBS-Bridge-Token",token).GET().build();eq(client.send(good,HttpResponse.BodyHandlers.ofString()).statusCode(),200,"health auth failed");HttpRequest bad=HttpRequest.newBuilder(health).header("X-OBS-Bridge-Token","bad").GET().build();eq(client.send(bad,HttpResponse.BodyHandlers.ofString()).statusCode(),403,"bad token was accepted");URI traversal=URI.create("http://127.0.0.1:"+ChatBridgeService.PORT+"/v1/tasks/not-a-uuid/heartbeat");HttpRequest tr=HttpRequest.newBuilder(traversal).header("X-OBS-Bridge-Token",token).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString("{\"tabId\":1,\"conversationKey\":\"convX2345678\"}")).build();eq(client.send(tr,HttpResponse.BodyHandlers.ofString()).statusCode(),409,"invalid task id was not rejected");}});
    }

    static ChatBridgeService serviceWithChat(StateStore st,String key,int...tabs){ChatBridgeService s=new ChatBridgeService(st);s.replaceInventory(List.of(chat(key,"Chat","https://chatgpt.com/c/"+key,tabs)));return s;}
    static Map<String,Object> chat(String key,String title,String url,int...tabs){Map<String,Object>m=new LinkedHashMap<>();m.put("conversationKey",key);m.put("title",title);m.put("url",url);List<Integer>x=new ArrayList<>();for(int t:tabs)x.add(t);m.put("tabIds",x);return m;}
    static Core.ChangeSet changeSet(String id,String label){Core.ChangeSet c=new Core.ChangeSet();c.changeSetId=id;c.changeSetLabel=label;return c;}
    static Core.ReviewDiff review(Path p,String id,String text)throws Exception{Files.writeString(p,text,StandardCharsets.UTF_8);return new Core.ReviewDiff(id,p,Core.sha256(p),"HEAD");}
    static String ticket(Map<String,Object> claim){String url=String.valueOf(claim.get("payloadUrl"));return url.substring(url.indexOf("ticket=")+7);}
    static Path snapshotZip(Path p)throws Exception{try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(p))){put(z,"SNAPSHOT.json","{\"schemaVersion\":1,\"snapshotType\":\"local\",\"snapshotFolder\":\"snapshot/\"}\n");put(z,"BASE-COMMIT.txt","abc\n");put(z,"WORKING-TREE.diff","");z.putNextEntry(new ZipEntry("snapshot/"));z.closeEntry();put(z,"snapshot/a.txt","a");}return p;}
    static void put(ZipOutputStream z,String name,String text)throws Exception{z.putNextEntry(new ZipEntry(name));z.write(text.getBytes(StandardCharsets.UTF_8));z.closeEntry();}
    static void git(Path repo,String...args)throws Exception{List<String> c=new ArrayList<>();c.add("git");c.add("-C");c.add(repo.toString());c.addAll(List.of(args));Process p=new ProcessBuilder(c).redirectErrorStream(true).start();String out=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);if(p.waitFor()!=0)throw new AssertionError("git failed: "+out);}
    interface X{void run()throws Exception;}
    static void test(String name,X x){try{x.run();passed++;System.out.println("PASS "+name);}catch(Throwable e){failed++;System.out.println("FAIL "+name+" :: "+e);e.printStackTrace(System.out);}}
    static void expect(String code,X x)throws Exception{try{x.run();throw new AssertionError("Expected "+code);}catch(Core.ObsException e){eq(e.code,code,"error code");}}
    static void ok(boolean v,String m){if(!v)throw new AssertionError(m);}static void eq(Object a,Object b,String m){if(!Objects.equals(a,b))throw new AssertionError(m+" expected="+b+" actual="+a);}
    static void deleteTree(Path p){if(p==null||!Files.exists(p))return;try(var s=Files.walk(p)){s.sorted(Comparator.reverseOrder()).forEach(x->{try{Files.deleteIfExists(x);}catch(Exception ignored){}});}catch(Exception ignored){}}
}
