package obs.rpkg;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.zip.*;

public final class CoreTests {
    static int passed,failed; static final GitClient git=new GitClient();
    static Path tmp,repo,bare; static Core core; static String rawOrigin="https://github.com/example/testrepo.git",repoId="github:example/testrepo",reviewSha,mainCs;

    public static void main(String[] args) throws Exception {
        tmp=Files.createTempDirectory("obs-rpkg-java-tests-");
        try { setup(); runTests(); }
        finally { deleteTree(tmp); }
        System.out.println("RESULT passed="+passed+" failed="+failed);
        if(failed>0)System.exit(1);
    }

    static void setup() throws Exception {
        repo=tmp.resolve("repo");bare=tmp.resolve("remote.git");Files.createDirectories(repo);
        g(repo,"init","-b","main");g(repo,"config","user.name","OBS Test");g(repo,"config","user.email","obs@example.invalid");g(repo,"config","commit.gpgsign","false");
        write(repo.resolve("replace.txt"),"old");write(repo.resolve("delete.txt"),"gone");g(repo,"add",".");g(repo,"commit","-m","base");
        g(tmp,"init","--bare",bare.toString());g(repo,"remote","add","origin",rawOrigin);g(repo,"config","url."+bare.toUri()+".insteadOf",rawOrigin);
        core=new Core(new StateStore(tmp.resolve("state")));
    }

    static void runTests() throws Exception {
        mainCs=UUID.randomUUID().toString();PackageFixture pkg=makePackage(repoId,mainCs,"test changeset",List.of(op("replace.txt","replace","old","new"),op("delete.txt","delete","gone",null),op("add.txt","add",null,"added")));
        test("ACTION_PACKAGE_MISMATCH stops before mutation",()->{String action="OBS-ACTION/1\naction: apply-package\nname: mismatch\narchive: x.zip\npackageId: "+UUID.randomUUID();expect(Core.ACTION_PACKAGE_MISMATCH,()->core.applyAction(action,pkg.path,repo));eq(read(repo.resolve("replace.txt")),"old","mismatch mutated target");});
        test("REPOSITORY_MISMATCH stops before mutation",()->{PackageFixture p=makePackage("github:other/repo",UUID.randomUUID().toString(),"wrong repo",List.of(op("replace.txt","replace","old","bad")));expect(Core.REPOSITORY_MISMATCH,()->core.applyPackage(p.path,repo));eq(read(repo.resolve("replace.txt")),"old","wrong repo mutated target");});
        test("BASE_MISMATCH stops before mutation",()->{PackageFixture p=makePackage(repoId,UUID.randomUUID().toString(),"bad base",List.of(op("replace.txt","replace","not-old","bad")));expect(Core.BASE_MISMATCH,()->core.applyPackage(p.path,repo));eq(read(repo.resolve("replace.txt")),"old","base mismatch mutated target");});
        test("dirty unowned path is not adopted",()->{write(repo.resolve("replace.txt"),"dirty");try{expect(Core.STATE_DIVERGED,()->core.applyPackage(pkg.path,repo));}finally{write(repo.resolve("replace.txt"),"old");}});
        test("apply add replace delete; review includes untracked add; real index untouched",()->{Core.ApplyResult r=core.applyPackage(pkg.path,repo);eq(read(repo.resolve("replace.txt")),"new","replace result");ok(!Files.exists(repo.resolve("delete.txt")),"delete result");eq(read(repo.resolve("add.txt")),"added","add result");ok(Files.readString(r.review().diffPath()).contains("add.txt"),"untracked add absent from ReviewDiff");ok(gAllow(repo,"diff","--cached","--quiet").exitCode()==0,"real index changed");reviewSha=r.review().sha256();});
        test("path ownership conflict",()->{PackageFixture p=makePackage(repoId,UUID.randomUUID().toString(),"other",List.of(op("replace.txt","replace","new","other")));expect(Core.PATH_OWNERSHIP_CONFLICT,()->core.applyPackage(p.path,repo));});
        test("stale review blocks finalize",()->{write(repo.resolve("replace.txt"),"changed-after-review");try{expect(Core.REVIEW_STALE,()->core.finalizeChangeSet(mainCs,reviewSha,"x",repo));}finally{write(repo.resolve("replace.txt"),"new");}});
        test("clean-index boundary blocks finalize",()->{write(repo.resolve("unrelated.txt"),"staged");g(repo,"add","unrelated.txt");try{expect(Core.FINALIZE_FAILED,()->core.finalizeChangeSet(mainCs,reviewSha,"x",repo));}finally{g(repo,"reset","-q","--","unrelated.txt");Files.deleteIfExists(repo.resolve("unrelated.txt"));}});
        test("changed origin blocks finalize before commit/push",()->{g(repo,"remote","set-url","origin","https://github.com/evil/other.git");try{expect(Core.REPOSITORY_MISMATCH,()->core.finalizeChangeSet(mainCs,reviewSha,"x",repo));}finally{g(repo,"remote","set-url","origin",rawOrigin);}});
        test("finalize commits/pushes reviewed owned paths",()->{Core.FinalizeResult r=core.finalizeChangeSet(mainCs,reviewSha,"finalize test",repo);eq(r.changeSet().status,"Finalized","not finalized");eq(g(repo,"rev-parse","HEAD").first(),r.commitSha(),"commit mismatch");});
        test("add then delete continuation yields empty review and no-op Finalize",()->{String cs=UUID.randomUUID().toString(),label="net zero";PackageFixture add=makePackage(repoId,cs,label,List.of(op("ephemeral.txt","add",null,"temporary")));core.applyPackage(add.path,repo);PackageFixture del=makePackage(repoId,cs,label,List.of(op("ephemeral.txt","delete","temporary",null)));String headBefore=g(repo,"rev-parse","HEAD").first();Core.ApplyResult r=core.applyPackage(del.path,repo);ok(Files.size(r.review().diffPath())==0,"net-zero ReviewDiff was not empty");Core.FinalizeResult f=core.finalizeChangeSet(cs,r.review().sha256(),"net zero",repo);eq(f.changeSet().status,"Finalized","net-zero ChangeSet not finalized");ok(f.commitSha()==null,"net-zero Finalize created/recorded a commit");eq(g(repo,"rev-parse","HEAD").first(),headBefore,"net-zero Finalize changed HEAD");});
        test("filesystem link escape is rejected before outside mutation",()->{Path outside=tmp.resolve("outside-target"),link=repo.resolve("escape");Files.createDirectories(outside);createEscapeLink(link,outside);try{String cs=UUID.randomUUID().toString();PackageFixture p=makePackage(repoId,cs,"escape",List.of(op("escape/new.txt","add",null,"outside")));expect(Core.STATE_DIVERGED,()->core.applyPackage(p.path,repo));ok(!Files.exists(outside.resolve("new.txt")),"package mutated path outside repository");}finally{Files.deleteIfExists(link);}});
        test("post-commit handoff/settings failure remains SUCCESS",()->{write(repo.resolve("handoff.txt"),"before");g(repo,"add","handoff.txt");g(repo,"commit","-m","handoff base");String cs=UUID.randomUUID().toString();PackageFixture p=makePackage(repoId,cs,"handoff warning",List.of(op("handoff.txt","replace","before","after")));Path settings=tmp.resolve("state/settings.json");Files.writeString(settings,"{ broken json",StandardCharsets.UTF_8);Core.ApplyResult r;try{r=core.applyPackage(p.path,repo);}finally{Files.deleteIfExists(settings);}eq(r.code(),Core.SUCCESS,"handoff failure changed Apply result");eq(read(repo.resolve("handoff.txt")),"after","successful target rolled back");ok(core.getChangeSet(cs)!=null&&core.getChangeSet(cs).status.equals("Active"),"successful ChangeSet missing");ok(r.attempt().handoffWarning.contains("ReviewDiff handoff failed"),"handoff warning not surfaced");long success=core.getAttempts().stream().filter(a->p.packageId.equals(a.packageId)&&"SUCCESS".equals(a.result)).count();ok(success==1,"persisted attempt was not SUCCESS");});
        test("post-mutation required-state failure rolls files and ChangeSet back",()->{write(repo.resolve("rollback.txt"),"before");g(repo,"add","rollback.txt");g(repo,"commit","-m","rollback base");String cs=UUID.randomUUID().toString();PackageFixture p=makePackage(repoId,cs,"rollback test",List.of(op("rollback.txt","replace","before","after")));core.setAfterMutationHookForTests(()->{throw new Core.ObsException(Core.RESULT_MISMATCH,"forced after mutation");});try{expect(Core.RESULT_MISMATCH,()->core.applyPackage(p.path,repo));}finally{core.setAfterMutationHookForTests(null);}eq(read(repo.resolve("rollback.txt")),"before","target did not rollback");ok(core.getChangeSet(cs)==null,"new ChangeSet survived failed transaction");});
        test("push failure records one pending commit; changed origin blocks Retry; restored transport retries without second commit",()->{write(repo.resolve("push.txt"),"before");g(repo,"add","push.txt");g(repo,"commit","-m","push base");String cs=UUID.randomUUID().toString();PackageFixture p=makePackage(repoId,cs,"push recovery",List.of(op("push.txt","replace","before","after")));Core.ApplyResult ar=core.applyPackage(p.path,repo);Path offline=tmp.resolve("remote.git.offline");Files.move(bare,offline);try{expect(Core.FINALIZE_FAILED,()->core.finalizeChangeSet(cs,ar.review().sha256(),"pending push",repo));}finally{Files.move(offline,bare);}Core.ChangeSet pending=core.getChangeSet(cs);eq(pending.status,"CommittedPendingPush","pending state missing");String commit=pending.commitSha;g(repo,"remote","set-url","origin","https://github.com/evil/other.git");try{expect(Core.REPOSITORY_MISMATCH,()->core.retryPush(cs,repo));}finally{g(repo,"remote","set-url","origin",rawOrigin);}Core.FinalizeResult rr=core.retryPush(cs,repo);eq(rr.changeSet().status,"Finalized","retry did not finalize");eq(rr.commitSha(),commit,"retry changed commit");eq(g(repo,"rev-parse","HEAD").first(),commit,"HEAD changed during retry");});
        test("traversal path rejected",()->{PackageFixture p=makePackage(repoId,UUID.randomUUID().toString(),"bad",List.of(op("../evil.txt","add",null,"x")));expect(Core.PACKAGE_INVALID,()->core.readPackage(p.path));});
    }

    record Op(String path,String action,String base,String replacement){}
    record PackageFixture(Path path,String packageId){}
    static Op op(String p,String a,String b,String r){return new Op(p,a,b,r);}
    static PackageFixture makePackage(String rid,String cs,String label,List<Op> ops) throws Exception {String packageId=UUID.randomUUID().toString();Path zip=tmp.resolve("pkg-"+packageId+".zip");Map<String,Object> manifest=new LinkedHashMap<>();manifest.put("schemaVersion",1);manifest.put("packageId",packageId);manifest.put("changeSetId",cs);manifest.put("changeSetLabel",label);manifest.put("repositoryIdentity",rid);List<Object> oo=new ArrayList<>();for(Op o:ops){Map<String,Object> m=new LinkedHashMap<>();m.put("path",o.path);m.put("action",o.action);oo.add(m);}manifest.put("operations",oo);try(ZipOutputStream z=new ZipOutputStream(Files.newOutputStream(zip),StandardCharsets.UTF_8)){entry(z,"PACKAGE.json",Json.stringify(manifest).getBytes(StandardCharsets.UTF_8));for(Op o:ops){if(o.base!=null)entry(z,"base-files/"+o.path,o.base.getBytes(StandardCharsets.UTF_8));if(o.replacement!=null)entry(z,"replacement-files/"+o.path,o.replacement.getBytes(StandardCharsets.UTF_8));}}return new PackageFixture(zip,packageId);}
    static void entry(ZipOutputStream z,String name,byte[] data)throws Exception{ZipEntry e=new ZipEntry(name);z.putNextEntry(e);z.write(data);z.closeEntry();}

    interface Throwing{void run()throws Exception;}
    static void test(String name,Throwing f){try{f.run();passed++;System.out.println("PASS "+name);}catch(Throwable e){failed++;System.out.println("FAIL "+name+" :: "+e);if(Boolean.getBoolean("obs.tests.stack"))e.printStackTrace(System.out);}}
    static void expect(String code,Throwing f)throws Exception{try{f.run();throw new AssertionError("expected "+code+", got success");}catch(Core.ObsException e){if(!e.code.equals(code))throw new AssertionError("expected "+code+", got ["+e.code+"] "+e.getMessage());}}
    static void ok(boolean v,String m){if(!v)throw new AssertionError(m);}static void eq(Object a,Object b,String m){if(!Objects.equals(a,b))throw new AssertionError(m+" expected="+b+" actual="+a);}
    static void write(Path p,String s)throws Exception{Files.createDirectories(p.getParent());Files.writeString(p,s,StandardCharsets.UTF_8,StandardOpenOption.CREATE,StandardOpenOption.TRUNCATE_EXISTING);}static String read(Path p)throws Exception{return Files.readString(p,StandardCharsets.UTF_8);}
    static void createEscapeLink(Path link,Path target)throws Exception{try{Files.createSymbolicLink(link,target);}catch(UnsupportedOperationException|FileSystemException e){if(!System.getProperty("os.name","").toLowerCase(Locale.ROOT).contains("win"))throw e;Process p=new ProcessBuilder("cmd.exe","/d","/c","mklink","/J",link.toString(),target.toString()).redirectErrorStream(true).start();String out=new String(p.getInputStream().readAllBytes(),StandardCharsets.UTF_8);if(p.waitFor()!=0)throw new AssertionError("cannot create Windows junction: "+out);}}
    static GitClient.Result g(Path cwd,String...args){return git.run(cwd,Core.STATE_DIVERGED,args);}static GitClient.Result gAllow(Path cwd,String...args){return git.allow(cwd,Core.STATE_DIVERGED,args);}
    static void deleteTree(Path p){if(p==null||!Files.exists(p))return;try(var s=Files.walk(p)){s.sorted(Comparator.reverseOrder()).forEach(x->{try{Files.deleteIfExists(x);}catch(Exception ignored){}});}catch(Exception ignored){}}
}
